Test/Command/GenerateCommandTest.php, Test/Command/GeneratorModuleCommandTest.php, Test/Command/GeneratorPluginImageEffectCommandTest.php, Test/Generator/PluginBlockGeneratorTest.php, config/translations/console.en.yml, src/Command/CacheRebuildCommand.php, src/Command/ConfigDebugCommand.php, src/Command/ContainerDebugCommand.php, src/Command/DrushCommand.php, src/Command/GeneratorCommandCommand.php, src/Command/GeneratorControllerCommand.php, src/Command/GeneratorEntityCommand.php, src/Command/GeneratorFormCommand.php, src/Command/GeneratorModuleCommand.php, src/Command/GeneratorPluginBlockCommand.php, src/Command/GeneratorPluginImageEffectCommand.php, src/Command/GeneratorServiceCommand.php, src/Command/Helper/ConfirmationTrait.php, src/Command/Helper/FormTrait.php, src/Command/Helper/ModuleTrait.php, src/Command/Helper/RegisterCommandsHelper.php, src/Command/Helper/ServicesTrait.php, src/Command/RouterDebugCommand.php, src/Command/RouterRebuildCommand.php, src/Generator/PluginBlockGenerator.php, src/Generator/PluginImageEffectGenerator.php, src/Resources/skeleton/module/src/Plugin/Block/block.php.twig, src/Resources/skeleton/module/src/Plugin/ImageEffect/imageeffect.php.twig
* Refactor test classes
*  Add 'en' translation messages
* Add ConfirmationTrait
* Update RegisterCommandsHelper auto-discovery
* Replace text with translation keys on Traits
* Replace text with translation keys on Command classes
* Update plugin generators
* Update plugin generators twig templates
=> Translate commands

config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml
* Add fr messages file
* Add messages to es & pt files
=> Add messages

config.yml, src/Console/Application.php
* Update version number
* Update version number display, remove environment
=> Update version 0.6.1

Test/Command/GeneratorFormCommandTest.php, Test/Command/GeneratorPluginBlockCommandTest.php, src/Command/Helper/FormTrait.php, src/Resources/skeleton/module/src/Form/form.php.twig
Enable add select, radios, checkboxes fields in form, with option to add options values via generator command
=> Enable add select, radios, checkboxes fields in form generator

src/Resources/skeleton/base/class.php.twig
I think there is more of this kind but I'll keep searching
=> Fixed opening brace for class declaration.

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml
I think "Load services form the container." should be "Load services from the container." The other changes I'm pretty sure about.
=> review config messages

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml
Fix a few typos and colloquialisms in English.
=> add missing commands in es, fr, and pt console files. 

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml, src/Generator/PluginBlockGenerator.php, src/Resources/skeleton/module/src/Form/form.php.twig, src/Resources/skeleton/module/src/Plugin/Block/block.php.twig
For coding patterns I used these files:
core/modules/system/src/Plugin/Block/SystemMenuBlock.php
core/modules/book/src/Plugin/Block/BookNavigationBlock.php
modules/examples/block_example/src/Plugin/Block/ExampleConfigurableTextBlock.php
core/modules/aggregator/src/Plugin/Block/AggregatorFeedBlock.php
=> Mostly work on the block form.

composer.json, src/Command/ModuleDownloadCommand.php, src/Command/migrate_upgrade/MigrateExecuteMessageCapture.php
* Unused use statement should be avoided
* Unused method, property, variable or parameter
* Text files should end with a newline character
=> sensiolabs Test Fixes

src/Command/RestDebugCommand.php
We have some violations
https://insight.sensiolabs.com/projects/cc529050-789e-45f1-8f1f-38aaa78f9307/analyses/6
and with this PR should be fixed
https://insight.sensiolabs.com/projects/cc529050-789e-45f1-8f1f-38aaa78f9307/analyses/7
=> Removed commented code and unused variable.

Test/Generator/PluginBlockGeneratorTest.php, config/translations/console.en.yml, src/Command/Helper/FormTrait.php, src/Resources/skeleton/module/src/Plugin/Block/block.php.twig
Checkboxes are not perfect (http://prntscr.com/60p8r5). I can take care of them in another PR. Before this PR, block form values were not printing in the view block at all.
=> adds/fixes options for radios, select, and checkboxes in blocks

config/translations/console.en.yml, src/Command/GeneratorModuleCommand.php
* Add directory-exists message
* Replace ask with askAndValidate
=> Generate module module path ask ask and validate

config/translations/console.pt-br.yml
Here goes the translation for Brazilian portuguese.
=> Pt-br translation for DrupalAppConsole

config/translations/console.en.yml, src/Command/ContainerAwareCommand.php, src/Command/RestDebugCommand.php, src/Command/RestDisableCommand.php, src/Command/RestEnableCommand.php
@dmouse does a observation, and he suggest use `$this->getConfig Factory()` instead `\Drupal::config`
=> #372 rest disable and refactor

Test/Command/GeneratorModuleCommandTest.php, Test/Generator/ModuleGeneratorTest.php, config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml, src/Command/GeneratorModuleCommand.php, src/Generator/ModuleGenerator.php, src/Resources/skeleton/module/info.yml.twig, src/Utils/Validators.php
=> Issue #296 

config/translations/console.en.yml, src/Command/SiteModeCommand.php
=> 376 site mode command

src/Command/CacheRebuildCommand.php, src/Utils/Validators.php
Refactor for validate the cache. Moved cache validation to Validators.php.
Added validation in the execute step not not allow enter invalid caches.
=> Updated command cache:rebuild

config/translations/console.en.yml, src/Command/SiteModeCommand.php
=> #389 refactor site mode command class

config/translations/console.pt-br.yml, src/Command/CacheRebuildCommand.php, src/Command/GeneratorModuleCommand.php
Fix errors from report https://insight.sensiolabs.com/projects/cc529050-789e-45f1-8f1f-38aaa78f9307/analyses/12
=> Sensiolabs Test

config/translations/console.en.yml, src/Command/ConfigOverrideCommand.php
=> #398 [config:override] New command

Test/Command/GeneratorPermissionCommandTest.php, config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml, src/Command/GeneratorPermissionCommand.php, src/Command/Helper/PermissionTrait.php, src/Generator/PermissionGenerator.php, src/Utils/StringUtils.php, templates/module/permission.yml.twig
This generator still needs to write its permissions into the routing.yml, but otherwise it does the job. 
Since this is new code and new functionality, I'm going to write a test for this generator next.
=> Adds permissions generator

README.md
=> Updated README.md to clarify purpose, documentation and use

bin/console.php, src/EventSubscriber/ShowGeneratedFiles.php, src/EventSubscriber/ShowWelcomeMessage.php, src/EventSubscriber/WelcomeMessage.php
* Create new event subscriber classes
=> Remove the event listeners and replace with event subscriber

config/translations/console.hu.yml
Made after Drupal Camp London 2015
I pledge I will keep updated with the latest developments and translate new strings accordingly.
This is a great tool.
=> Hungarian translation

config/translations/console.hu.yml, src/Command/Helper/DrupalAutoloadHelper.php
Also fixes https://github.com/hechoendrupal/DrupalAppConsole/issues/473
I also made an ArchLinux AUR package: https://aur.archlinux.org/packages/drupal-console/
=> Updating Hungarian translation and fix for issue/473

src/Command/GeneratorCommandCommand.php, src/Command/GeneratorPluginBlockCommand.php, src/Utils/Validators.php
Validate the Class name for Command and PluginBlock generation.
+ Describe correct Class name rules as on php.net
=> #381: Validate input class-name for generate:Command and PluginBlock.

src/Generator/ModuleGenerator.php
DefaultController routing.yml prepend a leading forward slash to path property
=> #493 DefaultController routing.yml prepend a leading forward slash

src/Generator/ControllerGenerator.php
Check if $route param has leading forward slash.
=> #495 Prepend leading forward slash on route path

config/translations/console.en.yml, config/translations/console.es.yml, src/Command/GeneratorControllerCommand.php, src/Console/Application.php, src/Generator/ControllerGenerator.php, src/Generator/Generator.php, templates/module/routing-controller.yml.twig
Add verbose code output functionality
=> 497 add verbose code output

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.pt.yml, src/Command/SiteStatusCommand.php
=> #410 First version of site:status

templates/module/src/Entity/entity-content.php.twig
The default entity template should add a default form handler.
=> Add a default form handler.

config/translations/console.fr.yml
Optimizing some strings, adding new ones.
=> French traduction

templates/module/src/accesscontrolhandler-entity-content.php.twig
Sorry for the mess, I am still learning this pull request stuff
=> [generate:entity:content] checkCreateAccess template #539

templates/module/src/interface-entity-content.php.twig
This pull request will fix https://github.com/hechoendrupal/DrupalAppConsole/issues/535
=> 535 [generate:entity:content] ingroup tag is incorrect

src/Console/Application.php
For easier integration with Drush.
=> Change require_once to require when loading the Drupal autoloader

src/Console/Application.php
This allows Drush to use DrupalConsole to bootstrap.
After you merge this, I can add commits to #1337 that use this in Drush.
=> #589: Refactor the 'doRun()' method

config/translations/console.fr.yml
I've just sync the French translation file, and enhance some translations
=> French translation

Test/Command/GeneratorModuleCommandTest.php, Test/Generator/ModuleGeneratorTest.php, config/translations/console.en.yml, src/Command/GeneratorModuleCommand.php, src/Generator/ModuleGenerator.php, templates/module/composer.json.twig
Create composer.json in the module root.
=> Add composer.json to ModuleGenerator

config/translations/console.en.yml, src/Command/GeneratorAuthenticationProviderCommand.php, src/Generator/AuthenticationProviderGenerator.php, templates/module/src/Authentication/Provider/authentication-provider.php.twig
improved documentation inline for applies function
=> Fix Authentication provider generator

config/translations/console.en.yml, src/Command/ModuleInstallCommand.php
* Update english messages
* Merge duplicated functionality
* Fix typo misssing_dependencies with missing_dependencies
=> 622 Merge module and another module functionality

README.md, config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.hu.yml, config/translations/console.ro.yml, src/Command/RestDebugCommand.php
Fixt typo in option (autorization => authorization) and small tweaks to README.md to correspond to drupal-console-book and bring it up-to-date (FFW as sponsor and link to latest Drupal version, et)
=> Minor typo cleanup etc

config/translations/console.en.yml, src/Command/GeneratorThemeCommand.php, src/Generator/ThemeGenerator.php, templates/theme/info.yml.twig, templates/theme/theme.twig
=> Added new command to generate a Drupal 8 theme

config/translations/console.en.yml, src/Command/SiteStatusCommand.php
* Add new english messages
*Add system data hash_salt + console ver
* Add configuration data active + staging paths
=> Update site status

config/translations/console.en.yml, src/EventSubscriber/CallCommandListener.php
* #639 Add module_install english message
* #639 Skip module:install and show error message
=> Chain not installing module properly

src/Command/Helper/DrupalAutoloadHelper.php
Should fix some issues with drupal-composer from drupal-composer/drupal-project/issues/28
=> Require autoload.php instead core/vendor/autoload.php

Test/Console/ApplicationTest.php, src/Console/Application.php
* Validate input, commandName and isBooted
* Hack test to try Travis Build
=> Force test to try Travis Build

config/translations/console.en.yml, src/Command/GeneratorPluginRulesActionCommand.php, src/Generator/PluginRulesActionGenerator.php, templates/module/src/Plugin/RulesAction/rulesaction.php.twig, templates/module/system.action.action.yml
@jmolivas 
Can you please check this PR?
Thanks,
Sajal
=> #649 fixed ruleaction command

templates/module/composer.json.twig
The support path is set to project page, updating to issues page
=> Set proper path to support/issues

templates/module/links.task-entity-content.yml.twig
... otherwise the Delete tab is shown before Edit.
=> Add weight to entity delete task

templates/module/src/Entity/entity-content.php.twig
Related change record: https://www.drupal.org/node/2346455
=> Remove fieldable from ContentEntity annotation

config/translations/console.en.yml, src/Command/GeneratorModuleCommand.php, src/Command/MigrateExecuteCommand.php, src/Command/YamlMergeCommand.php
Create to sync translation files before a new release to avoid loose current translation and bring new changes.
=> New command to enable merge 2 or more yaml files

templates/module/src/Entity/entity-content.php.twig, templates/module/src/Entity/entity.php.twig
=> #663 Generated entity links should point to paths, not routes

src/Command/YamlMergeCommand.php
using function array_replace_recursive
=> Remplace recursive function to use php native function 

src/Config.php
Remove warning related with this message
PHP Notice:  Undefined index: commands in /Users/enzo/www/DrupalConsole/src/Config.php on line 55
=> Remove warning

bin/console.php, composer.json
locale is tried first, second local config to determine language
=> Enable function to determine language base in environment locale 

Test/BaseTestCase.php, Test/Command/GenerateCommandTest.php, Test/Command/GeneratorModuleCommandTest.php, Test/DataProvider/ModuleDataProviderTrait.php, Test/Generator/GeneratorTest.php, Test/Generator/ModuleGeneratorTest.php, config/dist/chain.yml, src/Command/GeneratorModuleCommand.php, src/Generator/ModuleGenerator.php
* Remove controller generation from generate:module
* Refactor GeneratorModuleCommandTest
=> Remove controller from module generation

templates/module/routing-entity.yml.twig, templates/module/src/Entity/entity.php.twig
This makes the config entity path consistent. See  https://github.com/hechoendrupal/DrupalConsole/issues/722
=> Set config entity path to admin/system/[entity name]

.php_cs
=> PHP fixer Symfony Level

Test/Command/GeneratorPluginTypeYamlCommandTest.php, config/translations/console.en.yml, src/Command/GeneratorPluginTypeYamlCommand.php, src/Generator/PluginTypeYamlGenerator.php, templates/module/plugin-yaml-services.yml.twig, templates/module/plugin.yml.twig, templates/module/src/yaml-plugin-manager-interface.php.twig, templates/module/src/yaml-plugin-manager.php.twig
This PR adds a new command to generate a plugin type with yaml discovery:
```
generate:plugin:type:yaml
```
=> Generate a plugin type with Yaml discovery

config/translations/console.en.yml, src/Command/ConfigImportSingleCommand.php
=> [config:import:single] Start of a new config import command.

config/translations/console.en.yml, config/translations/console.es.yml, src/Command/PasswordResetCommand.php, src/Command/UserLoginCleanAttemptsCommand.php
Added new UserLoginCleanAttemptsCommand. I added two @todo, please let me know what you think about them.
=> 769 clear failed login

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.hu.yml, config/translations/console.pt.yml, config/translations/console.ro.yml, src/Command/ContainerAwareCommand.php, src/Command/TestDebugCommand.php, src/Command/TestRunCommand.php
Fix debug by id output, added type of test and handle error for missing dependencies for test
=> Fix debug by id output, added type of test

src/Command/UserPasswordResetCommand.php
Execute command UserLoginCleanAttemptsCommand after user account reset its password.
=> #801 Added chain command to clear login failed attempts

composer.json, src/Command/SiteNewCommand.php
Using buzz client and php functions to download and save release file, replacing guzzle
=> Enable download of drupal outside drupal

src/Command/MigrateExecuteCommand.php
#823 Fix migration execute errors
=> #823 Fix migration execute errors

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.hu.yml, config/translations/console.pt.yml, config/translations/console.zh.yml, src/Command/Descriptor/TextDescriptor.php, src/Command/Helper/DescriptorHelper.php, src/Command/ListCommand.php, src/Console/Application.php
Added support to zh : Chinese traditional
=> Enhance app to have more control over console output to improve trans

config/translations/console.vn.yml
=> [translation] Add vn translation

src/Helper/KernelHelper.php
=> Check if $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] is defined.

config/translations/console.en.yml, src/Command/GeneratorCommandCommand.php, src/Command/UserLoginCommand.php, src/Utils/Validators.php
The command returns one time login urls.
By default the user is admin, but a uid can be specified.
=> [user:login] Add one time login command

templates/module/src/Plugin/Block/block.php.twig
Update options in block configuration values
=> [generate:plugin:block] Update form config options

templates/module/src/Form/form-alter.php.twig
Update options in form configuration values
=> [generate:form:alter] Update form options

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.hu.yml, config/translations/console.pt.yml, config/translations/console.ro.yml, config/translations/console.vn.yml, config/translations/console.zh.yml, src/Command/ConfigExportViewCommand.php, src/Helper/SiteHelper.php, src/Utils/Validators.php
- Enable export as optional config
- Get config type directory based in optional type
- Create config directory if doesn't exist
=> [config:export:view] Improve enabling export as optional config

templates/module/module.twig
The TWIG escape filter is more suitable for the purpose.
=> Escape user entered input using the twig filter.

src/Command/SiteStatusCommand.php
* Use render method to get string.
* Add try/catch to:
* Settings::getHashSalt()
* config_get_config_directory()
=> [site:satatus] Fix command

templates/module/src/Entity/entity-content.php.twig, templates/module/src/interface-entity-content.php.twig
=> Hande the changed field properly. Fixes #945

src/Command/ContainerAwareCommand.php, src/Command/GenerateEntityBundleCommand.php, src/Generator/EntityBundleGenerator.php, src/Utils/Validators.php
=> 922 accept blank spaces in human readable name

config/translations/console.en.yml, config/translations/console.es.yml, config/translations/console.fr.yml, config/translations/console.hu.yml, config/translations/console.pt.yml, config/translations/console.ro.yml, config/translations/console.vn.yml, config/translations/console.zh.yml, src/Command/ContainerAwareCommand.php, src/Command/CronReleaseCommand.php
This command release lock in LockBackend service
=> [cron:release] Add command 

src/Command/ModuleDownloadCommand.php
Fix logic to dowload a specific version of module release
=> [module:download] Fix logic for module version

src/Console/Application.php
This fix issue on d.o. https://www.drupal.org/node/2499667
=> [console] Fix run console outside drupal root

config/translations/console.hi.yml
- Also introductory text translated.
=> Issue #976: [Language: Hindi] Application

config/translations/console.hi.yml
Please add hindi transslation.
=> hindi translation

templates/module/src/Plugin/Field/FieldFormatter/fieldformatter.php.twig
To reflect change in Drupal core: https://www.drupal.org/node/2543258
=> [generate:plugin:fieldformatter] Fix fieldformatter.php.twig

README.md, src/Command/AboutCommand.php
* Updated Supported Version in README and About command
=> [console] Supported Version outdated

src/Helper/DrupalHelper.php
Added the detection for a root on a Windows drive.
=> [console] Detect root on Windows machines

src/Command/SiteInstallCommand.php
* Use correct translation keys for langcode and db-type
* Fix spacing of method comments
* Update code comments to use correct option
=> Add minor fixes to site:install command

src/Command/ModuleDownloadCommand.php, src/Command/SiteNewCommand.php, src/Command/ThemeDownloadCommand.php
* Increase curl timeout.
* Remove unnecessary try/catch `(method_exists($client, 'get')` validation.
=> [console] Increase curl timeout

config/translations/es/theme.download.yml
he traducido:
*theme* → tema
*release* → versión
esto puede ser controvertido, acepto correcciones :)
=> spanish version theme.download.yml

templates/module/src/event-subscriber.php.twig
=> [event:subscriber] Fix generator

README.md
Just so it doesn't scroll left forever.
=> Updating line width in BASH Completion instructions of README

config/translations/en/generate.command.yml
Related to PR https://github.com/hechoendrupal/drupal-console-book/pull/104
=> [generate:command] Update labels,  to be more user friendly

config/translations/hi/init.yml, config/translations/hi/locale.translation.status.yml
2 files translated in this PR : 
init.yml
locale.translation.status.yml
=> [translation] Hindi init and locale.translation.status

config/translations/en/database.client.yml, config/translations/en/database.connect.yml, config/translations/es/db.client.yml, config/translations/fr/db.client.yml, config/translations/hu/db.client.yml, config/translations/pt/db.client.yml, config/translations/ro/db.client.yml, config/translations/vn/db.client.yml, config/translations/zh/db.client.yml
It was just making me hungry!!
Maybe I’m missing a joke and, if I am, sorry - I did look to see if anyone else had made same error.
=> Updating mentions of "lunch" to be "launch".

config/translations/es/locale.translation.status.yml
[translation] Spanish locale.translation.status
@GermancitoDC
=> [translation] Spanish locale.translation.status

config/translations/en/migrate.execute.yml, config/translations/en/site.install.yml, src/Command/Database/DatabaseTrait.php, src/Command/SiteInstallCommand.php
This PR allows to use sqlite on `site:install` command, and can be useful for #1184 :smile:
=> [site:install] sqlite support

config/translations/en/config.export.content.type.yml, config/translations/en/config.export.single.yml, config/translations/en/config.export.yml, config/translations/en/config.expot.view.yml, config/translations/en/config.import.yml, src/Command/Config/ExportCommand.php, src/Command/Config/ImportCommand.php, src/Command/Config/OverrideCommand.php
* ExportCommand:
* Set directory as option
* Add tar option
* Remove unused code
* ImportCommand:
* Rename and set as option config-file > file
* Remove copy-only option
* Add remove-files option
* OverrideCommand:
* Remove TableHelper
* Update translation messages
=> [config:*] Commands improvements

src/Command/Database/ClientCommand.php, src/Command/Database/ConnectCommand.php, src/Command/Database/ConnectTrait.php
* ClientCommand
* Implement resolveConnection changes
* ConnectCommand
* Implement resolveConnection changes
* ConnectTrait
* Update resolveConnection method
=> [database:*] Update resolveConnection method

templates/theme/theme.twig
* Removed or added spaces to meet coding standards.
* Short array syntax
* $variables array type hinting.
* Preprocess docblock referencing the template. https://www.drupal.org/node/1913208
=> Coding standards and cleanup for theme.twig

config/translations/ru/config.debug.yml, config/translations/ru/config.edit.yml, config/translations/ru/config.export.content.type.yml, config/translations/ru/config.export.single.yml, config/translations/ru/config.export.yml, config/translations/ru/config.expot.view.yml, config/translations/ru/config.import-single.yml, config/translations/ru/config.import.yml, config/translations/ru/config.override.yml
Translate several files, all for config
=> [tranlation] Russian config.* 

config/translations/en/site.install.yml, config/translations/es/site.install.yml, config/translations/fr/site.install.yml, config/translations/hi/site.install.yml, config/translations/hu/site.install.yml, config/translations/pt/site.install.yml, config/translations/ro/site.install.yml, config/translations/ru/site.install.yml, config/translations/vn/site.install.yml, config/translations/zh/site.install.yml, src/Command/Site/InstallCommand.php
Added support to use database provides in settings.php if is available
=> [site:install] Added support to use database provides in settings.php

config/translations/ru/cron.debug.yml, config/translations/ru/cron.execute.yml, config/translations/ru/cron.release.yml
Translate several files, all for cron
=> [translation] Russian cron

config/translations/ru/views.debug.yml, config/translations/ru/views.disable.yml, config/translations/ru/views.enable.yml
Translate several files, all for views
=> [tranlation] Russian views.* 

config/translations/es/generate.entity.bundle.yml, config/translations/es/generate.entity.config.yml, config/translations/es/generate.entity.content.yml, config/translations/es/generate.theme.yml
he traducido las cosas que he visto que estaban sin traducir de los ficheros nuevos.
«bundle» lo he dejado tal cual, no creo que tenga traducción directa en español.
comentarios, sugerencias, insultos ... bienvenidos xD
=> [translation] Spanish

config/translations/en/database.log.debug.yml, src/Command/Database/LogDebugCommand.php
=> #1399 Add a --reverse option to database:log:debug

templates/module/entity-content-page.php.twig
Deprecate function `\Drupal::l` see more about the deprecation at -  https://api.drupal.org/api/drupal/core%21lib%21Drupal.php/function/Drupal%3A%3Al/8
=> Fixes for #1465

templates/module/src/Entity/entity-content.php.twig
PR for #1391 issue,
Hope it helps
=> #1391: declare additionnal entity keys, Fix #1391

config/translations/pt_br/config.import-single.yml, config/translations/pt_br/config.import.yml, config/translations/pt_br/config.override.yml, config/translations/pt_br/cron.debug.yml, config/translations/pt_br/cron.execute.yml, config/translations/pt_br/cron.release.yml, config/translations/pt_br/database.client.yml, config/translations/pt_br/database.connect.yml, config/translations/pt_br/database.dump.yml
More translating some files to pt_br
=> [translation] pt-br

templates/module/composer.json.twig
Minor detail but save some 301s :)
=> [generate:module,theme] Add https and www to d.o project homepage in composer.json

config/translations/es/database.client.yml, config/translations/es/generate.controller.yml, config/translations/es/self-update.yml, config/translations/es/server.yml, config/translations/es/state.debug.yml, config/translations/es/state.override.yml
=> Novia713 spanish translation

Test/DataProvider/ConfigFormBaseDataProviderTrait.php, Test/DataProvider/FormDataProviderTrait.php, Test/Generator/ConfigFormBaseGeneratorTest.php, Test/Generator/FormGeneratorTest.php, config/translations/en/generate.form.yml, src/Command/Generate/FormAlterCommand.php, src/Command/Generate/FormCommand.php, src/Command/MenuTrait.php, src/Generator/FormGenerator.php, templates/module/links.menu.yml.twig
=> Generate menu links for admin config forms

config/translations/es/common.yml, config/translations/es/config.debug.yml, config/translations/es/create.nodes.yml, config/translations/es/create.terms.yml, config/translations/es/create.users.yml, config/translations/es/create.vocabularies.yml, config/translations/es/database.table.debug.yml, config/translations/es/database.table.drop.yml, config/translations/es/generate.controller.yml, config/translations/es/generate.form.yml, config/translations/es/generate.module.yml, config/translations/es/generate.theme.yml, config/translations/es/site.new.yml, config/translations/es/user.debug.yml, config/translations/es/user.delete.yml, config/translations/es/views.enable.yml
=> updated spanish translation

templates/module/module.twig
=> Removed trailing end-of-line. Fix #1687

config/translations/en/config.import-single.yml, config/translations/en/config.override.yml, config/translations/fr/about.yml, config/translations/fr/application.yml, config/translations/fr/cache.rebuild.yml, config/translations/fr/chain.yml, config/translations/fr/common.yml, config/translations/fr/config.debug.yml, config/translations/fr/config.edit.yml, config/translations/fr/config.export.content.type.yml, config/translations/fr/config.export.single.yml, config/translations/fr/config.export.view.yml, config/translations/fr/config.export.yml, config/translations/fr/config.import.yml
=> [translation] french - misc and config.*

config/translations/en/config.import-single.yml, config/translations/en/config.override.yml, config/translations/en/create.nodes.yml, config/translations/fr/config.import-single.yml, config/translations/fr/config.override.yml
I accidentally translated English sources files yesterday. 
This PR corrects my mistakes.
=> [translation] Fix accidentally impacted sources files 

templates/module/src/Plugin/Field/FieldFormatter/imageformatter.php.twig
This fixes #1691 by adding the cache namespace.
=> Fixes #1691

config/dist/chain/sample.yml
=> [chain] Add generate:controller and generate:form:config to sample.yml file.

config/dist/chain/quick-start.yml, config/translations/en/site.new.yml, src/Command/ProjectDownloadTrait.php, src/Command/Site/NewCommand.php, src/EventSubscriber/CallCommandListener.php, src/Helper/DrupalApiHelper.php
This is the ouput after with this PR.
* The `site-name` argument renamed to `directory`.
* Ask for directory if not provided as inline argument.
* Release list limited to 15.
=> [site:new] Add question when no site provided.

config/translations/hi/generate.controller.yml, config/translations/hi/generate.entity.config.yml, config/translations/hi/server.yml, config/translations/hi/state.override.yml
refactored the controller file translation and added translation fo entity config.
=> [translation] Hindi

templates/module/src/plugin-type-annotation-base.php.twig, templates/module/src/plugin-type-annotation-interface.php.twig, templates/module/src/plugin-type-annotation-manager.php.twig
=> Correct annotation plugin namespace in templates #952

config/translations/en/site.status.yml, src/Command/AboutCommand.php
Trying to fix this issue: https://github.com/hechoendrupal/DrupalConsole/issues/1824
=> Adding message to warn that Update Manager is not installed

config/translations/en/config.export.yml, config/translations/en/config.import.yml, src/Command/Config/ExportCommand.php, src/Command/Config/ImportCommand.php
Fixes issue #1786
Also fixes some other minor translation file issues.
I was going to take this a step further and implement the import process similar to what drush does, but I think this requires discussion and possibly a separate issue.
=> [config:import] Add directory option

config/translations/en/config.delete.yml, src/Command/Config/DeleteCommand.php
PR to adding the `config:edit` command.  #1366
=> [config:delete] Add new command, Fixes #1366.

src/Helper/CommandDiscoveryHelper.php
This addresses https://github.com/hechoendrupal/DrupalConsole/issues/1717 so that Commands added within themes can make use of Generators added within Themes.
Within a custom theme for Drupal 8, add a Command class that makes use of a Generator class. https://www.drupal.org/sandbox/mdrummond/2636658 is a good example. Right now, the Generator class is defined in the same file as the Command class. Remove the Generator definition from the Command class and uncomment the use statement for the Generator class that is defined in a separate file.
Within the Command Discovery process, this looks for Generator classes within themes and includes those classes.
Worked on this with Jesus at Drupal Camp Florida.
This requires Drupal 8.
=> [helper] Autoload Generator classes defined within themes.

config/translations/es/user.login.clear.attempts.yml
=> Updated bad spealling, Fix #2012

config/translations/en/image.styles.debug.yml, src/Command/ContainerAwareCommand.php, src/Command/Image/StylesDebugCommand.php
Regarding to the issue [#1922]
=> fix #1922 image styles debug [#1922]

config/translations/en/common.yml, config/translations/en/image.styles.flush.yml, src/Command/ContainerAwareCommand.php, src/Command/Image/StylesFlushCommand.php
Adding support for flush image.
=> fix #1922 Adding support for flush image styles

src/Command/State/OverrideCommand.php
Adding the interaction function to the state command for consistency across other commands.
=> Adding interaction into the state override command.

config/translations/en/application.yml
Changing `...It defines with what function...` to read as: 
`..It defines what function...`
=> minor grammatical update

src/Command/Generate/PluginFieldCommand.php
https://github.com/hechoendrupal/DrupalConsole/issues/2059
=> #2059 Correct suggestions for formatter plugin label and formatter plugin id

templates/module/src/Form/form.php.twig
Removed config.factory service extra in generate:form command
=> issue #2131 Removed config.factory service extra 

config/translations/en/plugin.debug.yml, src/Command/PluginDebugCommand.php
=> Add plugin:debug command

src/Command/FormTrait.php, src/Style/DrupalStyle.php
=> Fix select field issue in generate:form:config command. Fix: #2111

src/Command/Generate/ThemeCommand.php
Fixes https://github.com/hechoendrupal/DrupalConsole/issues/1430
=> Add the ability of using false on base theme.

src/Command/Generate/ConfigFormBaseCommand.php
This command does not use this class so let's remove it.
=> Removing an unused class

Test/BaseTestCase.php, src/Generator/CommandGenerator.php, src/Helper/SiteHelper.php, src/Helper/TranslatorHelper.php, templates/module/src/Command/command.php.twig
=> [console] Make custom module translation files structure same as Core commands

services.yml, src/Command/PluginDebugCommand.php
=> [plugin:debug] Register Command as a Service.

services.yml, src/Command/Views/PluginsDebugCommand.php
=> [views:plugin:debug] Work for #2225

services.yml, src/Command/Views/EnableCommand.php
=> [views:enable] Register Command as a Service.

services.yml, src/Command/Views/DebugCommand.php, src/Command/Views/DisableCommand.php
=> views:debug and views:disable - Register command as service.

config/translations/en/config.delete.yml, config/translations/es/config.delete.yml, src/Command/Config/DeleteCommand.php
=> [config:delete] Defined option named "all"

src/Command/Views/DisableCommand.php, src/Command/Views/EnableCommand.php
views:enable and views:disable does not have an interaction.
This pr creates an interaction that asks for which view is going to be enable/disable.
Only show views that are enable/disabled.
=> #2232 [views:enable] and [views:disable] Adding interaction

config/translations/tl/application.yml, config/translations/tl/breakpoints.debug.yml, config/translations/tl/cache.rebuild.yml, config/translations/tl/chain.debug.yml, config/translations/tl/chain.yml, config/translations/tl/complete.yml, config/translations/tl/config.debug.yml, config/translations/tl/views.disable.yml
=> [Translation] Tagalog

config/translations/en/module.update.yml, src/Command/Module/UpdateCommand.php
first aproximation to «module:update --composer»
for now, it does nothing without --composer
=> first aproximation to module:update --composer

config/translations/en/user.debug.yml, src/Command/User/DebugCommand.php
=> [user:debug] uid, username & mail filters as options

config/translations/en/user.role.yml, src/Command/User/RoleCommand.php
comand [user:role]
the mandatory args are:
1. "add"/"remove"
2. username
3. role [machine name]
//@TODO: load user by uid & email
//@TODO: discuss if username should accept an array
=> user-role for adding a role to a user [working]

config/translations/ca/generate.post.update.yml, config/translations/en/generate.post.update.yml, config/translations/es/generate.post.update.yml, config/translations/fr/generate.post.update.yml, config/translations/gu/generate.post.update.yml, config/translations/hi/generate.post.update.yml, config/translations/hu/generate.post.update.yml, config/translations/id/generate.post.update.yml, config/translations/ja/generate.post.update.yml, config/translations/ko/generate.post.update.yml, config/translations/mr/generate.post.update.yml, config/translations/pa/generate.post.update.yml, config/translations/pt_br/generate.post.update.yml, config/translations/ro/generate.post.update.yml, config/translations/ru/generate.post.update.yml, config/translations/tl/generate.post.update.yml, config/translations/vn/generate.post.update.yml, config/translations/zh_hans/generate.post.update.yml, config/translations/zh_hant/generate.post.update.yml, src/Command/Generate/PostUpdateCommand.php, src/Command/Module/DownloadCommand.php, src/Command/Update/ExecuteCommand.php, src/Generator/PostUpdateGenerator.php, src/Helper/DrupalHelper.php, templates/module/src/post-update.php.twig
Also fixes for generate:update and execute:update commands
=> [generate:post:update] New Command

Test/DataProvider/ControllerDataProviderTrait.php, Test/Generator/ControllerGeneratorTest.php, config/dist/chain/sample.yml, src/Command/Generate/ControllerCommand.php, src/Generator/ControllerGenerator.php, templates/module/routing-controller.yml.twig
- Validates path
- If router name is the same then concatenate with a random number
=> [generate:controller] Check if the route exits

src/Application.php
Awesome tool Jesus!
I updated to version 1.0.0-beta2 and get an error.
`PHP Warning:  preg_match(): Unknown modifier '/' in /home/tim/DrupalConsole/src/Application.php on line 202`
=> No preg_match delimiters.

config/translations/en/module.download.yml, config/translations/en/module.update.yml, services.yml, src/Command/Module/DownloadCommand.php, src/Command/Module/UpdateCommand.php, src/Command/ProjectDownloadTrait.php, src/Utils/ShellProcess.php
=> 2395-composer-fixes

config/translations/pa/chain.debug.yml, config/translations/pa/chain.yml
I have translated chain.debug.yml and chain.yml file to Punjabi.
As this is my first contribution so i have translated only two files. If It gets merge and I got familiar with the process then i will get back with the large number of changes. Please review and let me know is there anything that need to be change.
thanks.
=> Translate chain.debug and chain file to Punjabi

templates/module/templates/entity-with-bundle-content-add-list-html.twig
i don't know why the file wasn't present.
i've just restored the file «as is» in its place.
the command now seems to work ....
=> restoring the twig file

src/Utils/ShellProcess.php
corrected the format of the ProgressBar
i don't see any warning now
it comes from #2412
=> correct setFormat()

config/services/yaml.yml, src/Command/Yaml/DiffCommand.php, src/Command/Yaml/MergeCommand.php, src/Command/Yaml/SplitCommand.php, src/Command/Yaml/UpdateKeyCommand.php, src/Command/Yaml/UpdateValueCommand.php
=> [yaml] as a service

Test/Command/Generate/ServiceCommandTest.php, Test/DataProvider/ServiceDataProviderTrait.php, Test/Generator/ServiceGeneratorTest.php, config/translations/en/generate.service.yml, src/Command/Generate/ServiceCommand.php, src/Generator/ServiceGenerator.php
Provide an option to define a new path where we are going to store the services
=> Provide option to generate path for the services

templates/module/src/Entity/entity-content.php.twig
I just removed this from since the function preCreate on this template does the same thing
=> Remove unnecesary callback from template

config/translations/en/generate.breakpoint.yml, src/Command/Generate/BreakPointCommand.php, src/Generator/BreakPointGenerator.php
Command to generate  breakpoints on existing theme
=> [generate:breakpoint] New command for breakpoints

src/Command/Shared/FormTrait.php, templates/module/routing-form.yml.twig
Add text_format field to form and fix template since we were getting access denied when we try to load the form
=> [FormTrait] and [gerenare:form:*] Add text_format field and fix template for routing

config/translations/en/module.debug.yml, src/Command/Module/DebugCommand.php
Changed the disabled to installed and a few improvements..
Link to issue: #2443
=> Installed & Uninstalled

config/services/event.yml, config/services/misc.yml, config/translations/ca/event.debug.yml, config/translations/en/event.debug.yml, config/translations/es/event.debug.yml, config/translations/fr/event.debug.yml, config/translations/gu/event.debug.yml, config/translations/hi/event.debug.yml, config/translations/hu/event.debug.yml, config/translations/id/event.debug.yml, config/translations/ja/event.debug.yml, config/translations/ko/event.debug.yml, config/translations/mr/event.debug.yml, config/translations/pa/event.debug.yml, config/translations/pt_br/event.debug.yml, config/translations/ro/event.debug.yml, config/translations/ru/event.debug.yml, config/translations/tl/event.debug.yml, config/translations/vn/event.debug.yml, config/translations/zh_hans/event.debug.yml, config/translations/zh_hant/event.debug.yml, src/Command/Event/EventDebugCommand.php, src/Command/EventDebugCommand.php
=> New command event:debug

src/Command/Create/NodesCommand.php
=> issue #2483 fix for create:node

config/services/rest.yml, config/translations/en/rest.disable.yml, src/Command/Rest/DebugCommand.php, src/Command/Rest/DisableCommand.php, src/Command/Rest/EnableCommand.php, src/Command/Shared/RestTrait.php
Implementation of #2225 Ready to test/merge
=> [Rest] as a service

src/Command/Update/DebugCommand.php, src/Command/Update/EntitiesCommand.php, src/Command/Update/ExecuteCommand.php
I spot a small bug in ExecuteCommand and I tried to refactor the size of the functions.
=> [update:*] Fix & improve code standards

src/Command/Module/InstallCommand.php, src/Command/Shared/ModuleTrait.php
Check module's requirements , if the module has a requirement won't be installed
=> [module:install] Respect hook_requirements

src/Command/Multisite/NewCommand.php
This fixes some errors in the Multisite::NewCommand class with incorrect namespace references and variable typos.  I also changed the code to throw more specific exceptions instead of \Exception.
=> Fixes typos in variable names, throws more specific exceptions

config/translations/en/yaml.get.yml, src/Command/Yaml/GetValueCommand.php
=> Adding yaml:get:value command.

config/translations/ja/yaml.diff.yml, config/translations/ja/yaml.merge.yml, config/translations/ja/yaml.split.yml, config/translations/ja/yaml.update.yml
Thank you for the great project! 
I'd like to contribute to this project on Japanese translation after I heard this from blauerberg. This is my first pull request to this project and I'd like to this to be reviewed well before accepting. Thank you in advance.
=> [translation] Translate yaml-related interface text to Japanese.

config/services/field.yml, config/translations/en/field.info.yml, src/Command/Field/InfoCommand.php
Creating new PR for #1863 after git knowledge fail;) Will close old one.
=> Listing entity field info - code adapted from http://dgo.to/field_report module

templates/module/src/Authentication/Provider/authentication-provider.php.twig
Some minor issues with code style in the authentication provider template.
=> [template] Authentication provider code style

config/translations/en/config.export.yml, src/Command/Config/ExportCommand.php
this is my proposition a «info» msg with the path into it
=> 2586 config export

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/EventSubscriberCommand.php, src/Command/Generate/PermissionCommand.php, src/Command/Shared/ModuleTrait.php, src/Command/Shared/PermissionTrait.php, src/Generator/PermissionGenerator.php
[this comes form [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-247089962)]
all working except 
//@TODO: 
```
$this->generator->setLearning($learning);
$this->generator->generate($module, $permissions);
```
=> 2679 permission generator

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/HelpCommand.php, src/Command/Generate/ModuleCommand.php, src/Generator/HelpGenerator.php
working for me
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-246973055)
=> 2679 help generator

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/AuthenticationProviderCommand.php, src/Command/Generate/BreakPointCommand.php, src/Command/Module/InstallDependencyCommand.php, src/Command/Shared/ThemeBreakpointTrait.php, src/Generator/BreakPointGenerator.php
BreakPointCommand generator registered in container. It's working for me.
This comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-246799944) at #2679
=> 2679 breakpoint generator

src/Bootstrap/DrupalKernel.php
In every command I execute I see one annoying warning. This fix the problem.
=> Fix warning

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/AuthenticationProviderCommand.php, src/Command/Generate/FormAlterCommand.php, src/Command/Generate/PluginBlockCommand.php, src/Command/Generate/ServiceCommand.php, src/Command/Generate/UpdateCommand.php, src/Command/Shared/ServicesTrait.php, src/Generator/PluginBlockGenerator.php
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-247788896)
=> generate:plugin:block

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/PluginCKEditorButtonCommand.php, src/Generator/PluginCKEditorButtonGenerator.php
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-247846689)
=> generator ckeditor button

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/EntityBundleCommand.php, src/Generator/EntityBundleGenerator.php
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-247859785)
=> entity bundle generator

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/EntityCommand.php, src/Command/Generate/EntityConfigCommand.php, src/Command/Generate/EntityContentCommand.php, src/Command/Generate/PluginFieldCommand.php, src/Extension/Extension.php, src/Generator/EntityConfigGenerator.php, src/Generator/EntityContentGenerator.php
//@TODO
- learning option
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-247865003)
=> 2679 entity generator

config/services/drupal-console/generate.yml, config/services/drupal-console/generator.yml, src/Command/Generate/PluginConditionCommand.php, src/Generator/PluginConditionGenerator.php
this comes from [here](https://github.com/hechoendrupal/DrupalConsole/issues/2679#issuecomment-248246285)
=> plugincondition generator

src/Command/Shared/LocaleTrait.php
https://github.com/hechoendrupal/DrupalConsole/issues/2637#issuecomment-244536592
PR for needed string at https://github.com/hechoendrupal/drupal-console-en/pull/13
=> rerolled & related to 

.gitignore, config/services/drupal-console/site.yml, src/Command/Site/ImportLocalCommand.php
Hi Enzo, this is the site:import:local  you helped me with. Thanks!
=> Adding site:import:local as a service

src/Command/Migrate/ExecuteCommand.php, src/Command/Migrate/SetupCommand.php, src/Command/Shared/MigrationTrait.php
Migration plugin with files doesn't work, because can't allocate the drupal directory webroot folder/path
=> Enable pass configutation to migration plugins

templates/module/src/TwigExtension/twig-extension.php.twig
=> [generate:twig:extension] Make class extends proper class, fix #2788

config/services/drupal-console/generate.yml, src/Command/Generate/FormCommand.php
inyect services in generate:form [NOT WORKING YET]
=> related to #2769

.travis.yml
=> Run phpunit on travis script step

composer.json, composer.lock
Related #2798 
To use Drupal classes into a test, we need to add drupal/core in dev requirements.
=> Add drupal/core to dev requirements

config/services/drupal-console/misc.yml, src/Command/PermissionDebugCommand.php
This is WIP! Please do not merge yet!
I'll be working on it! thanks for your patience!
=> [permission:debug] new command #2895

src/Extension/Extension.php, src/Generator/ControllerGenerator.php
Use new name in Controller Generator. Fixes #2881
=> Rename getControllerDirectory() to getControllerPath() in Ext Mgr

src/Command/DevelDumperCommand.php, src/Command/Yaml/MergeCommand.php
Also fix devel:dumper issue when devel module is not available
=> [yaml:merge] Improvide interactive UI

composer.json
re https://github.com/acquia/lightning-project/issues/15
=> Update symfony/dom-crawler constraints

config/services/drupal-console/feature.yml, src/Command/Features/DebugCommand.php, src/Command/Features/ImportCommand.php, src/Command/Shared/FeatureTrait.php
**Changes**
- Add new features:debug command 
- Add new features:import command
=>  Add new commands to process features.

src/Generator/AuthenticationProviderGenerator.php, src/Generator/BreakPointGenerator.php, src/Generator/ControllerGenerator.php, src/Generator/EntityBundleGenerator.php, src/Generator/EntityConfigGenerator.php, src/Generator/EntityContentGenerator.php, src/Generator/EventSubscriberGenerator.php, src/Generator/FormAlterGenerator.php, src/Generator/FormGenerator.php, src/Generator/HelpGenerator.php, src/Generator/PluginCKEditorButtonGenerator.php, src/Generator/PluginConditionGenerator.php, src/Generator/PluginViewsFieldGenerator.php, src/Generator/PostUpdateGenerator.php, src/Generator/RouteSubscriberGenerator.php, src/Generator/ServiceGenerator.php, src/Generator/ThemeGenerator.php, src/Generator/TwigExtensionGenerator.php, src/Generator/UpdateGenerator.php
(minimal, whitespace only) Almost half of the generators had incorrect whitespace around the some comments.
=> Nick wilde1990 generator white space fixes

config/services/drupal-core/migrate.yml, src/Command/Migrate/ExecuteCommand.php, src/Command/Migrate/RollBackCommand.php, src/Command/Shared/MigrationTrait.php
**Changes**
- Add new command migrate:rollback
- Update MigrationTrait to fix bug with migrate:execute command
**Notes:**
PR for translation at https://github.com/hechoendrupal/drupal-console-en/pull/64
=> Add migrate rollback command.

composer.json
Issue:
https://github.com/hechoendrupal/drupal-console/issues/3093
=> 3093: change symfony/dom-crawler to  >=2.7 <3.2

config/services/drupal-console/generate.yml, src/Command/Generate/CacheContextCommand.php, src/Generator/CacheContextGenerator.php, templates/module/src/cache-context.php.twig
This PR adds the missing required dependency (extension manager). This also add service options in command and formats code and fixes/corrects the few typos which were found during fixing this
=> Adding missing required dependency

src/Command/Module/InstallCommand.php, src/Command/Shared/ModuleTrait.php
After last update module requirements are not properly verified, and most modules fail to install.
=> Cannot install modules due to improperly checked requirements.

templates/module/src/Form/form.php.twig
I found this one while I was generating some forms.
=> update an old reference of t()

src/Command/Site/StatusCommand.php
=> Fixes #2787: Make sure all modules are loaded before executing site:status

templates/module/src/Form/form.php.twig
When generating a form the code contains a few minor whitespace problems. This PR fixes them.
=> Fix whitespace in generated forms

composer.json
fixes hechoendrupal/drupal-console#3272
=> Relax dependency on doctrine/collections

src/Command/Generate/ThemeCommand.php, src/Command/Shared/ThemeRegionTrait.php, src/Generator/ThemeGenerator.php, templates/theme/info.yml.twig, templates/theme/libraries.yml.twig
**Changes:**
- Add option to generate another libraries using generate:theme command
- Update theme.info file to include new libraries
- Add new twig template to generate libraries file
=> [generate:theme] Add option to generate libraries.

src/Command/Create/NodesCommand.php
Fix issue https://github.com/hechoendrupal/drupal-console/issues/3307
=> [creates:nodes] Minor update for command. Fix #3307

templates/module/src/Entity/interface-entity-content.php.twig, templates/module/src/listbuilder-entity-content.php.twig
In the interfrace-entity-content.php.twig file
=> Fix #3176 and also remove unused libraries.

src/Command/Site/InstallCommand.php
in the install site command, Re: https://github.com/hechoendrupal/drupal-console/issues/3340
=> Use Console's DrupalFinder for constructing Drupal object

templates/module/src/Entity/Form/entity-settings.php.twig
Related to https://github.com/hechoendrupal/drupal-console/issues/3364
=> [BUGFIX #3364] Updated generate:entity command.

src/Command/Generate/CacheContextCommand.php
Changes for parameter cache-context done. Please pull the code.
=> Parameter cache-context fixed

src/Command/Config/OverrideCommand.php
Please pull this code to fix the indentation on Override Command
=> Override Command properly indented

src/Command/Config/OverrideCommand.php, src/Command/Config/ValidateCommand.php, src/Command/Config/ValidateDebugCommand.php
Please pull those changes for validate command and validate command debug.
=> Validate command

src/Utils/AnnotationValidator.php, src/Utils/TranslatorManager.php
Adding library support in order to make the translates work properly.
=> Read translation library

src/Command/Generate/ServiceCommand.php
Generate services command parameters changed to standard names.
=> Generate service command parameters changes to standard

src/Command/Generate/ModuleFileCommand.php, src/Command/Taxonomy/DeleteTermCommand.php, src/Command/Theme/DebugCommand.php, src/Command/Theme/DownloadCommand.php, src/Command/Theme/InstallCommand.php, src/Command/Theme/UninstallCommand.php, src/Command/User/CreateCommand.php, src/Command/User/LoginCleanAttemptsCommand.php, src/Command/User/PasswordHashCommand.php, src/Command/User/PasswordResetCommand.php
Indentation for multiple commands according to standard.
=> [console] Indent commands options.

src/Command/Shared/MenuTrait.php
Please merge those translations to change it according to Form Command tranlations.
=> Translations changed to the same in form command

config/services/drupal-console/debug.yml, config/services/drupal-console/views.yml, src/Command/Debug/ViewsPluginsCommand.php
=> Move views:plugins:debug to debug:views:plugins

config/services/drupal-console/debug.yml, config/services/drupal-console/views.yml, src/Command/Debug/ViewsCommand.php
Issue 3392 still present on after this update.
=> Move views:debug to debug:views

config/services/drupal-console/debug.yml, config/services/drupal-console/image.yml, config/services/drupal-console/libraries.yml, config/services/drupal-console/module.yml, config/services/drupal-console/queue.yml, config/services/drupal-console/router.yml, config/services/drupal-console/theme.yml, src/Command/Debug/ImageStylesCommand.php, src/Command/Debug/LibrariesCommand.php, src/Command/Debug/ModuleCommand.php, src/Command/Debug/QueueCommand.php, src/Command/Debug/RouterCommand.php, src/Command/Debug/ThemeCommand.php
Commands moved:
Move theme:debug to debug:theme
Move router:debug to debug:router
Move queue:debug to debug:queue
Move libraries:debug to debug:libraries
Move module:debug to debug:module
Move image:styles:debug to debug:image:styles
=> 3380 relocate debug commands

config/services/drupal-console/cron.yml, config/services/drupal-console/database.yml, config/services/drupal-console/debug.yml, config/services/drupal-console/entity.yml, config/services/drupal-core/breakpoint.yml, src/Command/Debug/BreakpointsCommand.php, src/Command/Debug/CronCommand.php, src/Command/Debug/DatabaseLogCommand.php, src/Command/Debug/DatabaseTableCommand.php, src/Command/Debug/EntityCommand.php
Commands moved:
Move entity:debug to debug:entity
Move entity:debug to debug:entity
Move database:table:debug to debug:database:table
Move cron:debug to debug:cron
Move breakpoints:debug to debug:breakpoints
=> 3380 relocate to debug

src/Command/Config/ExportCommand.php
=> [config:*] Fix translation keys.

config/services/drupal-console/cache.yml, config/services/drupal-console/config.yml, config/services/drupal-console/debug.yml, src/Command/Debug/CacheContextCommand.php, src/Command/Debug/ConfigCommand.php, src/Command/Debug/ConfigSettingsCommand.php, src/Command/Debug/ConfigValidateCommand.php, src/Command/Debug/MultisiteCommand.php, uninstall.services.yml
Commands moved:
Move cache:context:debug to debug:cache:context
Move cache:context:debug to debug:cache:context
Move config:settings:debug to debug:config:settings
Move config:validate:debug to debug:config:validate
Move multisite:debug to debug:multisite
=> 3380 relocate to debug config

config/services/debug.yml, config/services/feature.yml, config/services/migrate.yml, config/services/rest.yml, config/services/simpletest.yml, src/Command/Debug/FeaturesCommand.php, src/Command/Debug/MigrateCommand.php, src/Command/Debug/RestCommand.php, src/Command/Debug/TestCommand.php
Move module specific commands to debug namespace:
Move migrate:debug to debug:migrate
Move rest:debug to debug:rest
Move test:debug to debug:test
Move features:debug to debug:features
=> 3380 relocate to debug module commands

src/Command/Taxonomy/DeleteTermCommand.php
Related to https://github.com/hechoendrupal/drupal-console/issues/3419
PR for translation at https://github.com/hechoendrupal/drupal-console-en/pull/116
=> Updated taxonomy:term:delete  command.

src/Command/Generate/BreakPointCommand.php, src/Command/Generate/CacheContextCommand.php, src/Command/Generate/CommandCommand.php, src/Command/Generate/ControllerCommand.php, src/Command/Generate/EntityConfigCommand.php, src/Command/Generate/EntityContentCommand.php, src/Command/Generate/FormCommand.php, src/Command/Generate/HelpCommand.php, src/Command/Generate/ModuleFileCommand.php, src/Command/Generate/PluginCKEditorButtonCommand.php, src/Command/Generate/PluginConditionCommand.php, src/Command/Generate/PluginMailCommand.php, src/Command/Generate/PluginMigrateProcessCommand.php, src/Command/Generate/PluginMigrateSourceCommand.php, src/Command/Generate/PluginSkeletonCommand.php, src/Command/Generate/PostUpdateCommand.php, src/Command/Generate/ProfileCommand.php, src/Command/Generate/RouteSubscriberCommand.php, src/Command/Generate/TwigExtensionCommand.php, src/Command/Generate/UpdateCommand.php
* Adding aliases for generate commands.
=> Adding Aliases for Generate Commands.

src/Command/Module/UninstallCommand.php
=> Allow removing modules installed by profile.

src/Command/Generate/CommandCommand.php, src/Generator/CommandGenerator.php, templates/module/src/Command/command.php.twig
**Changes**
- Updated generate:command adding the option to add  interact method.
PR for translation at https://github.com/hechoendrupal/drupal-console-en/pull/133
=> Updated generate:command

src/Command/Config/EditCommand.php
=> Fall back to environment editor if not set in console config

src/Command/Queue/RunCommand.php
=> Fix queue:run (#3486)

src/Command/Database/RestoreCommand.php
This depends on the gunzip command being available.
=> Support .sql.gz files as input files

src/Bootstrap/Drupal.php, src/Bootstrap/DrupalUpdateKernel.php, src/Command/Update/ExecuteCommand.php
=> [console] Fix #3505: Too few arguments to function on hook updates.

src/Command/Database/DumpCommand.php
This will keep dump order and avoid afternoon an morning mix
=> change dump name to 24 hour format

src/Command/Module/InstallCommand.php, src/Command/Module/UninstallCommand.php, src/Command/Theme/InstallCommand.php, src/Command/Theme/UninstallCommand.php
Similar to #3408. Use interfaces for dependency injection.
=> Use interfaces for DI.

templates/module/src/Plugin/Block/block.php.twig
=> Fix block plugin output

config/services/create.yml, config/services/debug.yml, config/services/role.yml, services.yml, src/Command/Create/RolesCommand.php, src/Command/Debug/RolesCommand.php, src/Command/Role/NewCommand.php, src/Utils/Create/RoleData.php
[debug:roles] New command. Display all aplication roles
[create:roles] New command. Create dummy roles
[role:new] New command. Create application role
=> [console] Create roles commands

src/Command/Entity/DeleteCommand.php
Add `--all` to `entity:delete` (#3599).
=> [entity:delete] Add --all option. (#3599)

src/Command/Config/ExportContentTypeCommand.php
add --remove-uuid and --remove-config-hash to config:export:content:type - fixes #3622
=> add --remove-uuid and --remove-config-hash to config:export:content:type - fixes #3622

src/Command/Config/ExportContentTypeCommand.php
check that the content type exists - fixes #3626
=> check that the content type exists - fixes #3626

src/Command/Config/ExportSingleCommand.php
offer module as an interactive option in config:export:single - fixes #3631
=> offer module as an interactive option in config:export:single - fixes #3631

src/Command/Site/StatusCommand.php
Make the strings theme_default and theme_admin  translatable
=> Replace strings theme_default and theme_admin with translations for them

src/Command/User/LoginUrlCommand.php, src/Command/User/PasswordResetCommand.php, src/Command/User/UserBase.php
**Changes** 
- Add options to load user name & user id for upr command.
=> [user:*] Updates for user commands

src/Command/Generate/PluginRestResourceCommand.php, src/Utils/Validator.php, templates/module/src/Plugin/Rest/Resource/rest.php.twig
- Add validator of HTTP methods;
- Move list of http methods to separate method and add settings for it;
- Change twig template to generate the methods based on HTTP methods accordingly;
=> [generate:plugin:rest:resource] Add validator of HTTP methods. Move list of http methods to separate

src/Command/Shared/ThemeRegionTrait.php
The var $validators is not used, must be removed
=> Remove unused variables

src/Command/Generate/ThemeCommand.php, src/Command/Shared/ArrayInputTrait.php
1) Add new trait ArrayInputTrait, which will parse nested data.
2) Switch multi value options to array to handle them properly, when receive params through the options
3) Fix the methods, which parses the key:value data
4) Fix the logic when we don't use interaction mode.
=> [console] Add new trait ArrayInputTrait, which will parse input nested data.

src/Command/Generate/AjaxCommand.php, src/Command/Generate/AuthenticationProviderCommand.php, src/Command/Generate/BreakPointCommand.php, src/Command/Generate/CacheContextCommand.php, src/Command/Generate/CommandCommand.php, src/Command/Generate/ControllerCommand.php, src/Command/Generate/EntityBundleCommand.php, src/Command/Generate/EntityConfigCommand.php, src/Command/Generate/EntityContentCommand.php, src/Command/Generate/EventSubscriberCommand.php, src/Command/Shared/ServicesTrait.php, src/Generator/AjaxCommandGenerator.php, src/Generator/AuthenticationProviderGenerator.php, src/Generator/BreakPointGenerator.php, src/Generator/CacheContextGenerator.php, src/Generator/CommandGenerator.php, src/Generator/ControllerGenerator.php, src/Generator/EntityBundleGenerator.php, src/Generator/EntityConfigGenerator.php, src/Generator/EntityContentGenerator.php, src/Generator/EventSubscriberGenerator.php, src/Generator/HelpGenerator.php, src/Generator/ModuleFileGenerator.php, src/Generator/ModuleGenerator.php
1) Implement GeneratorInterface
2) Refactoring of Generators
=> Implementation of generator interface

src/Command/Generate/FormAlterCommand.php, src/Command/Generate/FormCommand.php, src/Command/Generate/PluginBlockCommand.php, src/Generator/HelpGenerator.php, templates/module/src/Form/form-alter.php.twig, templates/module/src/Form/form-config.php.twig, templates/module/src/Form/form.php.twig, templates/module/src/Plugin/Block/block.php.twig
1) Add support of nested data
2) Update twig templates : Add more fields options and checks for them
=> 3515 form trait input multi values

src/Command/Generate/PluginBlockCommand.php, src/Extension/Manager.php, templates/module/src/Plugin/Block/block.php.twig
Fix the bug with missing default_code
=> Adding ArrayInput trait. Add spaces for concatenation.

src/Command/Generate/AjaxCommand.php, src/Generator/AjaxCommandGenerator.php, templates/module/module-libraries.yml.twig
**Changes**
- Include new option for the custom js file
- Update generated files with the new option 
PR for translations at https://github.com/hechoendrupal/drupal-console-en/pull/166
=> [console] Add new option for generate ajax command.

src/Command/Create/CommentsCommand.php, src/Command/Create/NodesCommand.php, src/Command/Create/RolesCommand.php, src/Command/Create/TermsCommand.php, src/Command/Create/UsersCommand.php, src/Command/Create/VocabulariesCommand.php, src/Utils/Create/CommentData.php, src/Utils/Create/NodeData.php, src/Utils/Create/RoleData.php, src/Utils/Create/TermData.php, src/Utils/Create/UserData.php, src/Utils/Create/VocabularyData.php
Improve errors (Exceptions) handling for commands creating content and etc.
=> [create:*]  Create content exception. Fix #3779

composer.json
=> Make symfony/thanks a suggestion rather than a hard requirement

src/Extension/Manager.php, src/Utils/Validator.php
1) Fix warning 
2) Update the missing translation string with the correct one
=> Fix link check. Update validator translation string

src/Command/Database/ConnectCommand.php, src/Command/Shared/ConnectTrait.php
Make it possible use not only default target for db connections
=> [database:connect] Add new arguments key and target.

src/Generator/EntityContentGenerator.php, templates/module/src/Controller/entity-controller.php.twig, templates/module/src/Entity/entity-content.php.twig, templates/module/src/entity-storage.php.twig, templates/module/src/interface-entity-storage.php.twig
Remove translations related code if we didn't choose entity as translatable
=> 3275 remove translation code

src/Command/User/UserBase.php
=> Fix issue #3898 [user:password:reset] Notice when reseting the user password

src/Command/Module/UninstallCommand.php
=> Fix [module:uninstall] Deprecated each() function #3908

src/Command/Create/NodesCommand.php
Fixes #3914 
Here is a possible solution.
=> [create:nodes] Using a default language code

src/Extension/Extension.php, src/Generator/ControllerGenerator.php
Needs testing
https://github.com/hechoendrupal/drupal-console/issues/3998
=> Fix for #3998

templates/module/src/Entity/entity-content.php.twig, templates/module/src/Entity/interface-entity-content.php.twig
Make use of [Published/Unpublished API for content entities](https://www.drupal.org/node/2830201)
=> Use EntityPublishedTrait

config/services/user.yml, src/Command/User/UnblockCommand.php
This PR add a new command to allow you to unblock a user blocked.
=> Allow unblocking a blocked user.

src/Command/Site/InstallCommand.php
This Pr fixed the issue https://github.com/hechoendrupal/drupal-console/issues/4004
=> [site:install] Add error message to failed connection

src/Command/Shared/ExportTrait.php
This PR should be fix https://github.com/hechoendrupal/drupal-console/issues/4021
=> [config:export:view] Fixed override info.yml

src/Utils/Validator.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4029
=> [generate:module] Fixed dependencies validation

templates/module/src/Form/form-config.php.twig, templates/module/src/Form/form.php.twig, templates/module/src/Plugin/Block/block.php.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3970
And fix the commands that have inputs to render
=> [templates] Updated text_format to get the value

src/Command/Database/AddCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4040
=> [database:add] Hide the dbpass on interactive mode

src/Command/Router/RebuildCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3969
=> [router:rebuild] Handle unsuccessful rebuild

config/services/generate.yml, src/Command/Generate/ModuleCommand.php, src/Command/Generate/ThemeCommand.php, src/Utils/Site.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3886
=> [generate:module] Show multisite dir to generate

src/Command/Site/InstallCommand.php
Fix typo of https://github.com/hechoendrupal/drupal-console/pull/4049
=> [site:install] Fixed typo

config/services/multisite.yml, uninstall.services.yml
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4048
=> [services] Relocated multisite services

src/Command/Site/InstallCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4052
=> [site:install] Change dbFile if the installation is a multisite

src/Command/Generate/EntityContentCommand.php, src/Generator/EntityConfigGenerator.php, src/Generator/EntityContentGenerator.php, templates/module/src/Entity/entity-content.php.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/1120
=> [generate:entity:content] Enabled has-form option

src/Command/Generate/EntityContentCommand.php, src/Command/Module/UninstallCommand.php, src/Command/Update/ExecuteCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/1872
=> Fix module uninstall translation

src/Bootstrap/Drupal.php, src/Command/Update/ExecuteCommand.php
This PR should fix the last comment about the base path https://github.com/hechoendrupal/drupal-console/issues/2002
=>  [boostrap] Enabled the uri base path

src/Command/Generate/ControllerCommand.php, src/Utils/Validator.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/2080
=> [generate:controller] Validate if the class file is already exist

src/Command/Generate/ControllerCommand.php, src/Command/Update/ExecuteCommand.php, src/Utils/Validator.php, templates/module/src/Entity/entity-content.php.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/2166
=> [generate:entity:content] Fixed coding standard errors

src/Command/Site/InstallCommand.php
=> [site:install] #4079 Exit code issue fix

config/services/config.yml, src/Command/Config/ExportEntityCommand.php, src/Command/Shared/ExportTrait.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4081
=> [config:export:content:type] Exported the title field

src/Command/Create/NodesCommand.php, src/Utils/Create/NodeData.php
This PR implement this issue https://github.com/hechoendrupal/drupal-console/issues/3140
=> [create:nodes] Added the revision option

templates/module/module-file.twig, templates/module/permission.yml.twig
This PR contains code standard for the following commands:
```
generate:module:file
generate:permissions
```
=> [templates] Add code standard to module file and permissions

src/Command/Module/InstallCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console-book/issues/389
=> [module:install] Fixed composer key trans

src/Command/Generate/PluginBlockCommand.php, src/Generator/PluginBlockGenerator.php, templates/module/module-block-twig-template-append.twig, templates/module/src/Plugin/Block/block.php.twig, templates/module/templates/plugin-block-html.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3467
=> [generate:plugin:block] Add template option

src/Command/Generate/ThemeCommand.php, src/Generator/ThemeGenerator.php, templates/theme/info.yml.twig
This PR should be fix https://github.com/hechoendrupal/drupal-console/issues/3471
=> [generate:theme] Add --base-theme-regions option

src/Generator/PluginFieldWidgetGenerator.php, templates/module/schema.yml.twig, templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3432
=> [generate:plugin:fieldwidget] Add schema file

templates/module/src/Entity/entity-content.php.twig
This should be fix https://github.com/hechoendrupal/drupal-console/issues/4112
=> [generate:entity:content] Fix when owner is false

templates/module/src/Entity/entity-content.php.twig
https://github.com/hechoendrupal/drupal-console/issues/4084
=> [generate:entity:content] Change to EditorialContentEntityBase

README.md
=> Fix urls of #Download section

config/services/theme.yml, src/Command/Shared/ProjectDownloadTrait.php, src/Command/Theme/InstallCommand.php, src/Command/Theme/ThemeBaseCommand.php, src/Utils/Validator.php
This added feature works similarly to how "module: install" works, 
To install a theme using the release version when it is not found.
Thanks.
=> Add option install theme with release version

templates/module/templates/plugin-block-html.twig
https://twig.symfony.com/doc/2.x/tags/for.html
=> [generate:plugin:block] Fixed block template using incorrect item and sequence order in 'for' loop.

src/Command/Generate/EntityContentCommand.php, src/Generator/EntityContentGenerator.php
validate if the entity has bundles it's on true and create permissions https://github.com/hechoendrupal/drupal-console/issues/4162
=> [generate:entity:content] offers per bundle permissions for no-bundle entity

src/Command/User/LoginUrlCommand.php
Validate if the uri have https and return the link with https
https://github.com/hechoendrupal/drupal-console/issues/3935
=> [user:login:url] validate https on uri

src/Command/Config/ImportCommand.php, src/Command/Config/ImportSingleCommand.php
=> Issue 4303: Added missing parameter on ConfigImport instance.

src/Utils/DrupalApi.php
=> Fixes #4270: Call to undefined method

src/Command/Generate/ComposerCommand.php, src/Command/Generate/ModuleCommand.php, src/Generator/ComposerGenerator.php
Patch proposal to add package-path option to allow the generation of modules outside of the Drupal webroot: https://github.com/hechoendrupal/drupal-console/issues/4118#issuecomment-707162051
=> Add package path option.

src/Command/Config/ImportSingleCommand.php
Fixes issue: https://github.com/hechoendrupal/drupal-console/issues/4305
=> ImportSingleCommand::execute() will return 0 when command is successful.

templates/module/src/Controller/entity-controller.php.twig
The interface is located in the Entity folder
=> fix: bad namespace

templates/module/src/Controller/entity-controller.php.twig, templates/module/src/Entity/Form/entity-content-revision-delete.php.twig, templates/module/src/Entity/Form/entity-content-revision-revert.php.twig
Fix drupal 9 deprecations for generate:entity:content when content entity is revisionable
=> Fix drupal 9 deprecations in generateentitycontent]

src/Generator/PluginSkeletonGenerator.php
array_pop need to use reference, current will do the same work without error
=> Fix array_pop call

templates/module/src/Entity/Form/entity-content.php.twig, templates/module/src/Entity/entity-content.php.twig
Update with a new key on drupal core show_revision_ui
https://github.com/hechoendrupal/drupal-console/issues/4000
=> [generate:entity:content] show_revision_ui

templates/module/src/Entity/entity.php.twig
=> Issue 4280: Add config_export key to generated config entity annotation

templates/module/src/Controller/entity-controller.php.twig
Fixes fatal errors on link generation: https://github.com/hechoendrupal/drupal-console/issues/4317
=> Issue 4317: Fix content entity revision links.

src/Command/Config/ImportSingleCommand.php
=> [config:import:single] Prevent writing to DB before accessing ConfigImporter.

templates/module/src/entity-content-route-provider.php.twig
Route does not exist otherwise
=> fix: revision translation revert

templates/module/src/Entity/entity-content.php.twig
=> Issue 4284: [generate:entity:content] misses revision annotations
