- src/Resources/skeleton/module/src/Plugin/Block/block.php.twig
With latest version of Drupal 8.0.x  I got the following error
```
PHP Fatal error:  Class Drupal\multi_step\Form\MultiStepForm contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Drupal\Core\Form\ConfigFormBase::getEditableConfigNames)
```
I add in twig template for forms an empty implementation of method getEditableConfigNames()
> Resolve issue realted with abstract method getEditableConfigNames

- src/Resources/skeleton/module/src/Entity/entity-content.php.twig
After generate:entity:content, when I added new fields to the entity using the UI I get this error:
"There was a problem creating field NameOfTheField: The "string" plugin does not exist."
I have seen that in the node entity the type in the form is string_textfield and not string.
> Remove the error: The "string" plugin does not exist

- src/Resources/skeleton/module/links.action-entity-content.yml.twig
- src/Resources/skeleton/module/links.action-entity.yml.twig
- src/Resources/skeleton/module/links.menu-entity-content.yml.twig
- src/Resources/skeleton/module/routing-entity-content.yml.twig
- src/Resources/skeleton/module/routing-entity.yml.twig
- src/Resources/skeleton/module/src/Entity/Form/entity-content-delete.php.twig
- src/Resources/skeleton/module/src/Entity/entity-content.php.twig
- src/Resources/skeleton/module/src/Entity/entity.php.twig
- src/Resources/skeleton/module/src/Form/entity-delete.php.twig
- src/Resources/skeleton/module/src/Form/entity.php.twig
Tracking core:
- Replaced every .list with .collection
- Added the collection link template to the entity annotations
- Used the new preferred way of setting redirects:
```
-    $form_state->setRedirect('entity.{{ entity_name }}.list');
+    $form_state->setRedirectUrl(${{ entity_name }}->urlInfo('collection'));
```
Note that I didn't do the same to the delete form's getCancelUrl(), I only fixed the route name there, since the idea is to remove that whole class in another PR (core now has generic delete forms).
> The list routes are now named collection routes.

- config/translations/console.en.yml
- src/Command/ConfigExportCommand.php
This piece of code:
```
$this->addSuccessMessage(
$output,
sprintf($this->trans('commands.config.export.messages.directory'), $config_export_file)
);
```
is throwing an error:
```
PHP Fatal error:  Call to undefined function 
Symfony\Component\Console\Formatter\_drupal_get_last_caller() in 
/var/www/DrupalAppConsole/vendor/symfony/console/Symfony/Component/Console/
Formatter/OutputFormatter.php on line 37
```
It seems like $output var is obsolete in addSuccessMessage() as a string is need to be passed.
> [config:export] Export site configuration results in a PHP Fatal error

- templates/module/src/accesscontrolhandler-entity-content.php.twig
This is the fix for https://github.com/hechoendrupal/DrupalAppConsole/issues/536
> generate:entity:content produces inconsistent file annotation. #536

- src/Command/Helper/KernelHelper.php
n.b. no one calls KernelHelper::terminate yet.  Do this later.
This will insure that Drupal has a chance to write any changes to the db, etc.; without this, you'll sometimes need to run a cache rebuild.
Copied from DrupalBoot8 in Drush.
> Call kernel terminate in KernelHelper::terminate().

- src/Command/Helper/KernelHelper.php
- src/Console/Application.php
Drush bootstraps in multiple phases.  Some commands only need to access Drupal configuration, while others need a full bootstrap, with the kernel booted, etc.
Currently, Drush creates the kernel object during bootstrap configuration, but it does not call $kernel->boot() until the bootstrap full phase.  This refactor splits the Drupal Console initialization into two parts in order to allows Drush to continue to do this.
> Bootstrap refactor

- templates/module/src/Entity/entity-content.php.twig
Prevent "Link templates accepts paths, which have to start with a leading slash" exception when enabling content translation module
When you enable content translation module, and create a translatable entity with console, an exception is thrown by EntityType because there is no trailing slash at the begining of the path.
> [generate:entity:content] Prevent "Link templates accepts paths" exception with i18n

- composer.json
The Console is no longer a Drupal module, so its type should be project.
> Change type from drupal-module to project.

- src/Generator/PluginRestResourceGenerator.php
- templates/module/src/Plugin/Rest/Resource/rest.php.twig
At the moment a rest plugin is generated with incorrect id and label, the order of these parameters is wrong.
> Fix parameters order in generate() for rest plugin generation.

- .travis.yml
- src/Generator/Generator.php
- src/Utils/DrupalExtensionDiscovery.php
Fixes #658
@jmolivas I am not sure about the ``drupal chain`` build step, because the commands throughs an error but the exit code is 0.
> Fix Travis CI Integration

- templates/module/composer.json.twig
The naming convention for composer package types is ``drupal-module``, ``drupal-theme``, ``drupal-profile``etc.
> Set proper package type in composer.json

- templates/module/src/accesscontrolhandler-entity-content.php.twig
The operation is called "update" instead of "edit". Related docs from "EntityAccessControlHandler::checkAccess"
```
* @param string $operation
*   The entity operation. Usually one of 'view', 'update' or 'delete'.
```
> Fix access operation in AccessControlHandler

- templates/module/system.action.action.yml.twig
> adding the module name has dependency of the configuration object template

- templates/module/src/Entity/entity-content.php.twig
The [correct way](http://drupal.stackexchange.com/questions/162287/how-to-create-a-default-value-for-an-entity-base-field-in-drupal-8) to set a default value on an entity is to use `setDefaultValue()` and **not** to pass a `default_value` key in the base table defs.
See related [patch to examples module](https://www.drupal.org/node/2511182).
Nb. I think it is useful to keep this code (which sets a zero-length string as the default) in there as an example of how to provide a default.
> Remove deprecated default_value key from entity_value

- templates/module/src/Entity/Controller/listcontroller-entity-content.php.twig
- templates/module/src/Entity/Form/entity-content-delete.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Entity/entity-content-views-data.php.twig
This PR updates templates generated classes that still used t().
I'm chatting with Tim Plunkett in IRC right now about https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/module.twig
Which generates
```
/**
* Implements hook_help().
*/
function dcdtest_help($route_name, RouteMatchInterface $route_match) {
switch ($route_name) {
// Main module help for the dcdtest module.
case 'help.page.dcdtest':
$output = '';
$output .= '<h3>' . t('About') . '</h3>';
$output .= '<p>' . t('My Awesome Module') . '</p>';
return $output;
default:
}
}
```
> Convert t() to $this->t()

- box.json
This will decrease size of _console.phar_ by 40% approximately.
> [console] Compact php files in the phar archive

- templates/module/entity-content-page.php.twig
- templates/module/links.menu-entity-content.yml.twig
- templates/module/permissions-entity-content.yml.twig
- templates/module/routing-entity-content.yml.twig
- templates/module/src/Controller/entity-listbuilder.php.twig
- templates/module/src/Entity/Controller/listcontroller-entity-content.php.twig
- templates/module/src/Entity/Form/entity-content-delete.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Entity/Form/entity-settings.php.twig
- templates/module/src/Entity/entity-content-views-data.php.twig
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/Entity/entity.php.twig
- templates/module/src/Form/entity-delete.php.twig
- templates/module/src/accesscontrolhandler-entity-content.php.twig
- templates/module/src/interface-entity-content.php.twig
- templates/module/src/interface-entity.php.twig
- templates/module/src/plugin-type-annotation-manager.php.twig
- templates/module/templates/entity-html.twig
Since #743 went in the permissions for generated content entities now look a bit weird. If I create a "Book" entity type the permission titles now read:
* View book
* Edit book
* Delete book
* Adminster book
Because this is singular this is confusing. Which book am I allowed to edit? What if I want to give a role the permission to edit all books?
It would be better if we follow the pattern used for all permissions in core: display the plural form. Since we do not know how our entity is spelled in plural we can simply add the word "entities":
* View book entities
* Edit book entities
* Delete book entities
* Adminster book entities
In the future it might be interesting to ask the user for the plural form when generating entities, we might be able to use it elsewhere too. But for now this …
> [generate:entity:config] Improve spelling and grammar where the new entity labels are used

- templates/module/src/Plugin/Field/FieldFormatter/fieldformatter.php.twig
The closing bracket for the class is part of ``base/class.php.twig``.
> Remove closing bracket from FieldFormatter template

- .travis.yml
After reading a message on a previous build 
>This job ran on our legacy infrastructure. 
https://travis-ci.org/hechoendrupal/DrupalConsole/jobs/75182133
I decided to read the provided documentation link [Migrating from legacy to container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) and implemente the recomendation on this PR.
> [travis] migrate to container-based infrastructure

- composer.json
- composer.lock
Console is currently incompatible D8 HEAD. We should loose the twig dependency and allow higher minor versions of twig.
This should fix https://travis-ci.org/drupal-composer/drupal-project/jobs/75437467
> Loose twig dependency

- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Form/entity.php.twig
Currently the entity form code that is generated thinks that the return value of `Entity::save() ` is a boolean indicating success or failure, but this is not correct. This probably changed at some point in the past.
In current HEAD if a failure occurs during the saving of the entity an exception is thrown. Instead of a boolean, this method returns either `SAVED_NEW` or `SAVED_UPDATED`. We can use this information to provide a more fitting message.
> Wrong handling of Entity::save() return value

- templates/module/src/Entity/Form/entity-content.php.twig
Current documentation standards suggest to use `{@inheritdoc}` when overriding parent methods.
> Use {@inheritdoc}

- templates/base/interface.php.twig
Interfaces don't require use statements, even when type hinting specific classes. This also fixes an error in that {{service.interface}} is never defined and causes an error when drupal console tries to generate an interface.
> Remove use statements from generated Interfaces. Fixes #829

- bin/console.php
- src/Console/Application.php
- src/EventSubscriber/ShowGenerateDocListener.php
- src/Generator/EntityContentGenerator.php
- src/Generator/PermissionGenerator.php
- src/Helper/TwigRendererHelper.php
- templates/base/generate-doc.md.twig
This PR provides a new `--generate-doc` option to automate documentation generation.
The generated content is `markdown` format just to copy and paste into a file at the gitbook repository
https://github.com/hechoendrupal/drupal-console-book
> Add --generate-doc option

- config/translations/console.en.yml
- src/Command/GeneratorCommandCommand.php
- src/Command/UserLoginCommand.php
- src/Utils/Validators.php
New users that are unfamiliar with some of the conventions might be unaware that commands must end with the word Command and can get confused.
[generate:command] command will throw an error if such a name is requested.
> [generate:command] Updated the verification process of generated commands

- src/Helper/DrupalHelper.php
Console does not work with https://github.com/drupal-composer/drupal-project properly. Looks like refactoring to DrupalHelper introduced the bug.
Here is the failing Travis CI test. https://travis-ci.org/drupal-composer/drupal-project/jobs/81138968
> Use <root>/autoload.php

- README.md
- composer.json
- composer.lock
- config/translations/en/application.yml
- src/Application.php
- src/Command/CompleteCommand.php
- src/Command/InitCommand.php
- src/EventSubscriber/ShowCompletedMessageListener.php
- src/Generator/AutocompleteGenerator.php
- templates/autocomplete/console.fish.twig
- templates/autocomplete/console.rc.twig
This  PR autocomplete available commands with `<tab>` solves #679 
```
drupal init
source "$HOME/.console/console.rc" 2>/dev/null
ln -s ~/.console/drupal.fish ~/.config/fish/completions/drupal.fish
```
NOTE: if you already ran init command before, you can use --override option to override with the latest version from project. Make sure you save a backup copy of your file If you make changes.
> [console] Add tab autocomplete for commands

- templates/module/src/accesscontrolhandler-entity-content.php.twig
See https://www.drupal.org/node/2581447 , this results in an error when generating entities.
> [console] Entity access control handler no longer has a $langcode parameter

- src/Command/ThemeDownloadCommand.php
I was trying to download the zircon theme and was always getting timeout errors.  [Zircon](https://www.drupal.org/project/zircon) is about 2.66 Mb in size, which might not be an common occurrence.  Setting 10 seconds as the timeout was enough for me to be able to download it.
A couple of comments:
* Not sure if this is the proper fix, because network conditions vary across the world and some themes might be smaller or bigger. :/
* I noticed that `module:download` and `site:new` also create a `Buzz` browser (that uses curl as the client).  The construction/configuration of the `Buzz` client could be done, perhaps, in a helper.
* One more thing, the following code:
```php
try {
if (method_exists($client, 'get')) {
$response = $client->get($release_file_path);
} else {
```
will never …
> [theme:download] Increase curl timeout to 10 seconds

- bin/console.php
- composer.json
- composer.lock
- src/Command/ModuleDownloadCommand.php
- src/Command/SiteNewCommand.php
- src/Command/ThemeDownloadCommand.php
- src/Helper/HelperTrait.php
- src/Helper/HttpClientHelper.php
This PR adds the following changes:
* Remove Buzz
* Add Guzzle ~6.1
* Add HttpClientHelper to re-use download logic
* Update theme:download, site:new, and module:download commands
As described on #1072, downloading stuff is unreliable due to timeouts.  Apparently, `Buzz` does not allow an empty timeout setting (see [AbstractClient](https://github.com/kriswallsmith/Buzz/blob/master/lib/Buzz/Client/AbstractClient.php#L9) and [AbstractCurl](https://github.com/kriswallsmith/Buzz/blob/master/lib/Buzz/Client/AbstractCurl.php#L210-L215)), but I might be totally wrong.  If that's the case, please let me know.
So, I began testing with latest `Guzzle` successfully.  However, `Guzzle` was used previously on the project, but due to #767 it was replaced by `Buzz`.
I tried to replicate #767, but was …
> [helper] Re-add Guzzle for handling file downloads

- templates/module/routing-entity-content.yml.twig
- templates/module/routing-entity.yml.twig
- templates/module/routing-form.yml.twig
https://www.drupal.org/node/2224207
* Routes starting with "/admin" will get by default TRUE value assigned.
Which means by default, people should be okay. This is up for discussion whether to include or not :)
> [console] Add _admin_route to admin routes.

- README.md
SInce completion in Bash depends on [bash-completion](http://bash-completion.alioth.debian.org/) it should be noted.
> Add more complete instructions for Bash completion

- src/Command/SiteStatusCommand.php
The `locale` module does not use `TranslatableMarkup` strings for the title of its requirements, I'm pretty sure this is by design since its status can't depend on a locale being available or completely translated.
Fixes #1082
> [site:status] Check for translatable strings before calling render()

- src/Command/UpdateExecuteCommand.php
I'm in Drupal Console version 0.9.5.
When i make <code>drupal list</code>, i have
<code>
update
update:debug                      Display current updates available for the application
update:execute                    Display current updates available for the application
</code>
Seems UpdateExecuteCommand.php does some references to update:debug command. Replace them by execute.
> Bad copy/paste commands.update between debug and execute

- config/translations/en/application.yml
- src/Application.php
- src/Command/SiteStatusCommand.php
- src/Helper/DrupalHelper.php
- src/Helper/KernelHelper.php
- src/Helper/SiteHelper.php
This patch adds support for multisite Drupal environments as requested in Issue #755 .  It allows a user to specify which site to query or configure by using the --uri / -l command-line options (similar to drush).  The DrupalKernel code itself is utilized to determine which site and site path corresponds to the URI specified, avoiding possible duplication of code.
I also made a couple of other minor changes to avoid potential confusion:
- changed `$sitePath` in `SiteHelper` to `$siteRoot`
- renamed the `DRUPAL_SETTINGS` constant in `DrupalHelper` to `DEFAULT_SETTINGS_PHP`
> Add multisite support

- templates/module/src/Entity/Form/entity-content.php.twig
The current code for getting the entity langcode is broken, I'm not entirely sure this is the correct way of doing this but it does work when editing existing entities.
I also found https://www.drupal.org/node/2303877 which hints using "language()->getId()" should be avoided for content entities.
> Fixes the currently broken get of existing entity-langcode

- src/Command/Site/ModeCommand.php
When you use debug (or just auto_reload if you for some reason don't want debug on) the Twig cache doesn't get in your way. Disabling the Twig cache just makes for a slower development experience because each template needs to be compiled regardless of if it's been edited or not. Also, you can't easily debug/look at the compiled Twig templates (PHP classes) if they are not cached.
n/a I think, this is not a bug report.
Leave Twig cache alone! I think 99.9999% of the time developers should only touch debug, and leave auto_reload and cache alone. I would argue that auto_reload can be left as `null` but don't want to scope creep :)
> [site:mode] Do not disable Twig cache in dev mode

- templates/theme/theme.twig
This PR fix a syntax error when enable a theme created with the `generate:theme` command
> fix missing curly braces

- LICENSE
- README.md
I believe we need to add licence file to repository, it is a good practice. As I understand, DrupalConsole uses MIT licence. I prepared licence file and badge for it.
> [docs] Add licence file and badge for it

- src/Application.php
Symfony console application expected that method doRun() will return an exit code: zero if everything went fine, or an error code.
It prevents `The command terminated with an error status ()` error after every command in console.
> Add exit code for Application::doRun()

- src/Command/Views/DebugCommand.php
- src/Helper/DrupalHelper.php
- src/Helper/KernelHelper.php
- src/Helper/SiteHelper.php
- templates/gitbook/available-commands-list.md.twig
- templates/module/src/Plugin/Field/FieldFormatter/fieldformatter.php.twig
- templates/module/src/Plugin/Field/FieldType/fieldtype.php.twig
- templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
* Detected using insight by sensiolabs at:
https://insight.sensiolabs.com/projects/d0f089ff-a6e9-4ba4-b353-cb68173c7d90/analyses/82
> [console] Fix code warnings insight 82

- templates/module/src/entity-listbuilder.php.twig
- templates/module/src/listbuilder-entity-content.php.twig
Method EntityListBuilder::getLabel() is deprecated, use $entity->label() instead.
Link to the docs:  
https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Entity!EntityListBuilder.php/function/EntityListBuilder%3A%3AgetLabel/8
> [template] Fix deprecated function usage

- config/translations/en/server.yml
- src/Command/Develop/GenerateDocGitbookCommand.php
- src/Command/ServerCommand.php
```
$ drupal server
$ drupal server 127.0.0.1:8089
$ drupal --root=/Users/jmolivas/develop/drupal/sites/drupal8.dev server
```
> [server] Add new command

- templates/theme/theme.twig
Removing browser zoom on mobile devices is an anti-pattern that harms accessibility. There are many people that need to pinch and zoom in a browser to see things better. The default theme generation code should not remove that ability.
> Enable browser zoom on mobile devices

- Test/Generator/EntityContentGeneratorTest.php
- src/Generator/EntityContentGenerator.php
Adjusts paths in the EntityContentGenerator and updates test EntityContentGeneratorTest
> Generate forms in src/Form rather than src/Entity/Form

- config/translations/ru/database.client.yml
- config/translations/ru/database.connect.yml
- config/translations/ru/database.dump.yml
- config/translations/ru/database.log.clear.yml
- config/translations/ru/database.log.debug.yml
- config/translations/ru/database.restore.yml
- config/translations/ru/db.client.yml
Translate several files, all for db
> [translation] Russian db 

- config/translations/ru/update.debug.yml
- config/translations/ru/update.execute.yml
Translate several files, all for update
> [tranlation] Russian update.* 

- templates/module/links.menu-entity-config.yml.twig
- templates/module/links.menu-entity-content.yml.twig
- templates/module/links.task-entity-content.yml.twig
- templates/module/routing-entity-content.yml.twig
Improved code related with entity and bundle administration and links.
Check following image
> [generate:entity:content] Fixes

- composer.json
- composer.lock
- config/translations/en/self-update.yml
- src/Command/SelfUpdateCommand.php
Replace abandoned dependency `herrera-io/phar-update` with `padraic/phar-updater` this fix #806
> [self-update] Remove abandonded dependency fix #806

- .travis.yml
add PHP 7 to travis tests and flag it as "allowed_failure"
> #1396: add PHP7 to travis tests fix #1396

- Test/BaseTestCase.php
- Test/DataProvider/AuthenticationProviderDataProviderTrait.php
- Test/DataProvider/CommandDataProviderTrait.php
- Test/DataProvider/ConfigFormBaseDataProviderTrait.php
- Test/DataProvider/ControllerDataProviderTrait.php
- Test/DataProvider/EntityBundleDataProviderTrait.php
- Test/DataProvider/EntityConfigDataProviderTrait.php
- Test/DataProvider/EntityContentDataProviderTrait.php
- Test/DataProvider/EntityDataProviderTrait.php
- Test/DataProvider/FormDataProviderTrait.php
- Test/DataProvider/ModuleDataProviderTrait.php
- Test/DataProvider/PermissionDataProviderTrait.php
- Test/DataProvider/PluginBlockDataProviderTrait.php
- Test/DataProvider/PluginConditionDataProviderTrait.php
- Test/DataProvider/PluginFieldDataProviderTrait.php
- Test/DataProvider/PluginFieldFormatterDataProviderTrait.php
- Test/DataProvider/PluginFieldTypeDataProviderTrait.php
- Test/DataProvider/PluginFieldWidgetDataProviderTrait.php
- Test/DataProvider/PluginImageEffectDataProviderTrait.php
- Test/DataProvider/PluginImageFormatterDataProviderTrait.php
- Test/DataProvider/PluginRestResourceDataProviderTrait.php
- Test/DataProvider/PluginRulesActionDataProviderTrait.php
- Test/DataProvider/PluginTypeAnnotationDataProviderTrait.php
- Test/DataProvider/PluginTypeYamlDataProviderTrait.php
- Test/DataProvider/ServiceDataProviderTrait.php
- Test/DataProvider/ThemeDataProviderTrait.php
- src/Command/Config/EditCommand.php
Due to the similarity of the English word "temporary" and the Spanish word "temporal" there have been some mixups in the code.
> [console] Fix "temporary" spelling mistakes

- Test/DataProvider/ProfileDataProviderTrait.php
- Test/Generator/ProfileGeneratorTest.php
- config/translations/en/generate.profile.yml
- src/Command/Generate/ProfileCommand.php
- src/Generator/ProfileGenerator.php
- templates/profile/info.yml.twig
- templates/profile/install.twig
- templates/profile/profile.twig
> Add a generator for installation profiles.

- src/Helper/MessageHelper.php
Make MessageHelper implement LoggerInterface, so that it may be provided to any class that needs a Prs\Log-compatible logger.  The purpose here is to help enable code sharing, although at this particular time there is no candidate code to share.
I do find it somewhat troubling that Symfony/Console does not use Psr/Log, but since DrupalConsole already happens to have a MessageHelper, this extension is somewhat natural.
> Use Psr/Log

- .travis.yml
- config/dist/chain/quick-start.yml
The command ```drupal init --override``` is setting in quick-start chain the Drupal version 8.0.0 when the 8.0.1 is already available
> [Console] Updated quick start chain to use Drupal 8.0.1.

- config/dist/aliases.yml
This should said "theme" instead of themem. For this reason this will never run because there is not a such as thing as "themem"
> [aliases] theme download fix

- config/dist/aliases.yml
This is just a start there still some work for this PR to be complete. 
- We should add the ability of having the command aliases in the drupal list. For instance `drupal cache:build (cr)`. This will make user to easily learn the aliases.
- We should investigate and how to add a priority, to the aliases over the auto detection of command. 
- We should test all the commands to make sure that they are running property.
> Introducing aliases to all commands.

- src/Command/Config/ExportContentTypeCommand.php
This fixes the InvalidArgumentException: „The "content_type" argument
does not exist.“ I have not looked at the whole code and just tried
this out.
> Fix InvalidArgumentException on config:export:content:type

- templates/module/links.menu-entity-config.yml.twig
Menu's for content and bundle entities were not showing their menu items in admin/structure
> Removing extra space causing yml parsing error

- templates/module/links.menu-entity-content.yml.twig
Menu's for content and bundle entities were not showing their menu items in admin/structure
> Another extraneous space removal

- templates/module/src/Entity/entity.php.twig
When I create a new bundle and then I create a new entity with this, an exception appear:
```
Drupal\Component\Plugin\Exception\PluginNotFoundException: The "entity:name_entity:new_bundle" plugin does not exist
```
This is because after creating a new bundle, the cache is not cleared.
To fix this we can use ConfigEntityBundleBase.
> [generate:entity:content] Clear cache after creating a new bundle

- src/Command/FormTrait.php
With this, the console can autocomplete all input types available on the site
> [generate:form] Use ElementInfoManager to define all input types available

- src/Command/Command.php
- src/Command/Theme/DebugCommand.php
- src/Helper/CommandDiscoveryHelper.php
- src/Helper/SiteHelper.php
- src/Helper/TranslatorHelper.php
This PR is not functional as is, but I wanted to start a conversation to look at the possibility of having themes provide their own commands as well as modules. I found a few of the spots where changes need to be made in order for this to work, but I'm sure there are more.
One of the advantages of allowing themes to provide their own commands is so they could add their own generate functions to be able to generate sub-themes based on the specific needs of that particular theme. There may well be other cases where it would be useful for themes to provide Drupal Console custom commands as well.
> Search themes for commands as well as modules.

- src/Command/Module/DebugCommand.php
- src/Command/Module/DownloadCommand.php
- src/Command/Module/InstallCommand.php
- src/Command/Module/UninstallCommand.php
> Drupal style namespace module

- src/Command/Module/DownloadCommand.php
- src/Command/Rest/DebugCommand.php
- src/Command/Rest/DisableCommand.php
- src/Command/Rest/EnableCommand.php
> #1552 Drupal style namespace rest

- src/Command/Module/DownloadCommand.php
This PR uses `filterXPath` as exception suggested, on `module:download` command
> Fix Unable to filter with a CSS selector as the Symfony CssSelector exception

- templates/module/src/event-subscriber.php.twig
Really minor, missing newlines after properties and constructor. Adjusted newlines in getSubscribedEvents.
Before:
```php
<?php
/**
* @file
* Contains Drupal\test\TestDefaultSubscriber.
*/
namespace Drupal\test\EventSubscriber;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\EventDispatcher\Event;
use Drupal\Core\Session\AccountProxy;
/**
* Class TestDefaultSubscriber.
*
* @package Drupal\test
*/
class TestDefaultSubscriber implements EventSubscriberInterface {
/**
* Drupal\Core\Session\AccountProxy definition.
*
* @var Drupal\Core\Session\AccountProxy
*/
protected $current_user;
/**
* Constructor.
*/
public function __construct(AccountProxy $current_user) {
$this->current_user = $current_user;
}
/**
* {@inheritdoc}
*/
static function …
```
> Fix minor whitespace issues in generated event subscribers

- templates/module/module.twig
There is no need to have an empty hook_theme without any functionality when the user generate a module using the command generate:module.
> Fixes #1422: Remove the empty hook_theme from generate:module command.

- templates/module/src/Entity/Form/entity-content-delete.php.twig
Currently `ContentEntityConfirmFormBase` is being used but `ContentEntityDeleteForm` already provides the delete-specific information.
It is in fact superior to the current delete template because it properly handles entity translations.
I don't know if there is much of a use-case of overriding the delete form (i.e. I usually just reference `ContentEntityDeleteForm` in the entity annotation directly), but I went for the minimally invasive change for now.
> Use ContentEntityDeleteForm as a base class for content entity delete forms

- config/translations/en/generate.module.yml
- src/Command/Generate/ModuleCommand.php
Currently when running `generate:module` you get a called to undefined function `8.x` because there is an incorrect parameter that is being passed to the Symfony question helper. I implemented some basic validation of the core property.
> Fix the core version validation in generate:module

- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Entity/entity-content.php.twig
It's preferable to use the widget so people can override this properly from the UI.
I am not sure if we want to leave in the empty `buildForm()` for people or not, but left it in for now.
Also removed the `submit()` method from the form as that is obsolete and no longer being called anyway.
And used `parent::save()` instead of calling `$this->entity->save()` manually.
> Use the language_select widget instead of a custom form element for content entities

- README.md
We're getting some confusion from this so we need to flag it.  Might even want to prevent install with older PHP, but I'll leave that to smarter people.
> Add required PHP version to README.md

- src/Command/Generate/PluginFieldFormatterCommand.php
- templates/module/src/Plugin/Field/FieldType/fieldtype.php.twig
[generate:plugin:fieldformatter] Fixed Drupal style implementation   
[generate:plugin:fieldtype] Fixed Template output, the annotation commend cause an error parsing all field types
> [generate:plugin:fieldformatter] and [generate:plugin:fieldtype] 

- src/Command/Config/ExportContentTypeCommand.php
- src/Command/Config/ExportTrait.php
The config of the content type needs the id of the content type and not the label. 
It is also trying to create the file on another path that is not valid.
Also this fix the [config:export:view] command.
> [config:export:content:type] Fixed issue #1663

- config/translations/en/migrate.setup.yml
- src/Command/Migrate/SetupCommand.php
Add option to load Files Directory and setup the migration
> [migrate:setup] Fix to include directory files

- src/Helper/RemoteHelper.php
I am running Drupal in a Docker container with the SSH port forwarded to `2222`. I had to apply this patch to get remote Drush Console to connect successfully.
> [helper] Support alternate SSH port during login.

- src/Utils/DrupalExtensionDiscovery.php
A site with the patch for https://www.drupal.org/node/2156401 applied throws an error, since it defines ExtensionDiscovery::reset() as a static function.
> [console] Make DrupalExtensionDiscovery::reset() static

- templates/module/src/Entity/Form/entity-content.php.twig
When an entity that is generated with `console generate:entity:content` is edited, the user remains on the edit form after submitting the form. This is unexpected and gives the impression to the user that the submission of the form was unsuccessful, even though a success message is shown.
The standard practice in Drupal is that a user is redirected to the full page view of the entity, let's follow this practice for the content entities we generate.
This was reported by @idimopoulos as part of a usability test for the Joinup project of the European Commission.
> Show the entity page rather than the edit form after editing an entity.

- templates/module/src/accesscontrolhandler-entity-content.php.twig
Currently the code generated for a content entity's access handler always blindly allows access for unknown operations. This is a potential security risk as it might unintentionally disclose information when a new entity operation is implemented in the future.
It would be better to default to `AccessResult::neutral()` instead of `AccessResult::allowed()`. After all, if we do not know what the operation is doing we cannot allow nor deny. This is consistent with how it is implemented in core, see for example `EntityAccessControlHandler::checkAccess()`.
This was reported by @idimopoulos as part of a code review for the Joinup project of the European Commission.
> Default to neutral for entity access

- templates/module/plugin-yaml-services.yml.twig
When running YAML plugin generator, the manager and manager interface are in ````\Drupal\{{ module }}```` not the Plugin namespace.
See location of https://github.com/hechoendrupal/DrupalConsole/blob/master/templates/module/src/yaml-plugin-manager-interface.php.twig
> Plugin managers generated in root namespace

- config/translations/ca/site.status.yml
- config/translations/en/site.status.yml
- config/translations/es/site.status.yml
- config/translations/fr/site.status.yml
- config/translations/hi/site.status.yml
- config/translations/hu/site.status.yml
- config/translations/ja/site.status.yml
- config/translations/pt_br/site.status.yml
- config/translations/ro/site.status.yml
- config/translations/ru/site.status.yml
- config/translations/vn/site.status.yml
- config/translations/zh_hans/site.status.yml
- src/Application.php
- src/Command/AboutCommand.php
- src/Helper/SiteHelper.php
Added logic to print current drupal version if is available.
Check an example if drupal is detected
Check an example if drupal is not detected.
> [about] Improve output to render current drupal version

- src/Generator/EntityContentGenerator.php
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/entity-content-route-provider.php.twig
- This pull fix the issue #1739
- Also it set the setting form properly
- As now the [generate:module] command may not load the .module file, this command needs to detect this and then to create it if the entity has bundle.
> [generate:entity:content] Fixed route provider template #1739

- Test/Command/GeneratorEntityConfigCommandTest.php
- Test/Command/GeneratorEntityContentCommandTest.php
- Test/DataProvider/EntityConfigDataProviderTrait.php
- Test/DataProvider/EntityContentDataProviderTrait.php
- Test/DataProvider/EntityDataProviderTrait.php
- Test/Generator/EntityConfigGeneratorTest.php
- Test/Generator/EntityContentGeneratorTest.php
- Test/Generator/EntityGeneratorTest.php
- config/translations/en/generate.entity.config.yml
- config/translations/en/generate.entity.content.yml
- src/Command/Generate/EntityCommand.php
- src/Command/Generate/EntityConfigCommand.php
- src/Command/Generate/EntityContentCommand.php
- src/Generator/EntityConfigGenerator.php
- src/Generator/EntityContentGenerator.php
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/Entity/entity.php.twig
> Fixes #1813: Add base_path option for entity generation

- config/translations/en/config.export.single.yml
- src/Command/Config/ExportSingleCommand.php
- src/Command/ContainerAwareCommand.php
Adds the boolean option, stealing some logic from features for calculating dependencies.
Adds return types to ContainerAwareCommand and the protected class members for functions used in this command.
Fixes #1817
> [config:export:single] Add include dependencies option

- config/translations/en/config.diff.yml
- src/Command/Config/DiffCommand.php
New command.
Outputs a table of config changes between active configuration and a directory which can either be passed in or interactively chosen from a list of core's $config_directories.
Option ````--reverse```` to get a reverse output (i.e diff SOURCE ACTIVE)
Should be extended later with a verbose option to print the actual changes, possible in another table column, more likely in a big ugly list :)
Fixes #1821
> [config:diff] Add new command.

- src/Command/Site/InstallCommand.php
This same behavior has the installer via web
> [site:install] Account mail may be the same as defined for site mail

- templates/module/links.action-entity-content.yml.twig
In the view of an entity, the action link "Add {entity}" is displayed. This should only be displayed in the collection.
> [generate:entity:content] Remove the action add link for canonical link

- src/Command/Generate/FormAlterCommand.php
- templates/module/src/Form/form-alter.php.twig
Related with non webprofiler installation
> [generate:form:alter] fix issue metadata.unset  and inline form inputs #1661

- templates/module/src/Authentication/Provider/authentication-provider.php.twig
> [generate:authenication:provider] EntityManager is deprecated. #1874

- templates/module/src/Controller/controller-add-page.php.twig
- templates/module/src/Controller/controller-entity.php.twig
I have tested this by running 
drupal generate:entity:content
and using it by visiting
/admin/structure/default_entity_type/add
All seems to work fine.
> #1875 [generate:entity:content] EntityManager is deprecated.

- src/Command/ModuleTrait.php
- src/Helper/SiteHelper.php
Currently we can only generate code for modules. This PR allows to generate code for install profiles as well.
This fixes issue https://github.com/hechoendrupal/DrupalConsole/issues/1515.
> Support generating code for installation profiles.

- config/translations/en/database.log.clear.yml
- config/translations/en/database.restore.yml
- src/Command/Database/ConnectTrait.php
- src/Command/Database/DumpCommand.php
- src/Command/Database/RestoreCommand.php
Added ability for sites using 'pgsql' driver to use the "database" commands. Successfully tested all "database" commands with Postgres 9.4. Restore command works on an existing DB, but throws an error if db tables don't already exist. This seems to be a general issue with Drupal 8 support for Postgres and the different method (compared to MySQL) Postgres dumps a database.
> Postgres support for database commands

- config/translations/en/state.delete.yml
- src/Command/Config/DeleteCommand.php
- src/Command/State/DeleteCommand.php
This command works except the error if there is not that state is not available in the system.
I have comment this code out ....
``````
$keyValue = $this->getService('keyvalue');
if (!$keyValue->exists($name)) {
$io->error(
sprintf(
$this->trans('commands.state.delete.messages.state-not-exists'),
$name
)
);
return 1;
}
``````
> [state:delete] Add new command, working progress of #1968

- src/Helper/DrupalApiHelper.php
- src/Utils/Create/Base.php
- src/Utils/Create/Nodes.php
- src/Utils/Create/Terms.php
- src/Utils/Create/Users.php
- src/Utils/Create/Vocabularies.php
**Problem/Motivation**
EntityManager is deprecated and will be removed  before drupal 9.0.x 
In this PR  I just replace entityManager  in favor of  entityTypeManager.
We could even replace: 
`$node = $this->entityTypeManager->getStorage('node')->create(...)`
to
`$node = Node::create(...)`
I will create a another PR later.
> [helper] replace entityManager to entityTypeManager

- config/translations/en/create.comments.yml
- src/Command/Create/CommentsCommand.php
- src/Helper/DrupalApiHelper.php
- src/Utils/Create/Comments.php
**Problem/Motivation**
I've been working lately in some issues related with the comment module, and this command is handy  for me.
> [create:comments] Add new command.

- src/Command/Site/InstallCommand.php
Software version:
Drupal Console (0.10.12) | Drupal (8.0.3)
Command executed:
drupal site:install --langcode=it --db-type=sqlite --db-file=sites/default/files/.ht.sqlite standard
When you need sqlite and in command line you specify db-type and db-file the command in interactive mode asks you also db host.
I think that the problem is in the "if" at line number 165 of InstallCommand.php file.
https://github.com/hechoendrupal/DrupalConsole/blob/0.10.12/src/Command/Site/InstallCommand.php#L165
> Fix for check db-file and db-type for sqlite options

- config/translations/en/common.yml
- src/Command/FormTrait.php
- src/Generator/FormGenerator.php
- templates/module/config/install/field.default.yml.twig
- templates/module/src/Form/form-config.php.twig
When creating config forms, default values for fields are written on an YML file. Still needs work on field types other than textfields and textareas.
> Fixed default values for textfields and textareas on config forms.

- composer.json
This removes the dependency from `guzzle/guzzle`.
> Update the alchemy-fr/Zippy package

- templates/module/src/Plugin/Views/field/field.php.twig
Hey there.
First of all, thanks so much for this tool. It's pretty much the most awesome ever.
Just noticed a non-ideal output from the generation of a views field plugin. Here is a PR that makes it output code that passes Drupal coding standards and fixes one typo (generte => generate).
I see in the travis file that there is some effort to try and check Drupal CS on build. Will look at that, and see if I can help with something there :)
Have a great day!
> Fix all coding standard issues and some typos in views field plugin generation.

- templates/module/src/Plugin/Rest/Resource/rest.php.twig
OK, here I have actually changed a couple of things:
- There were to unused 'use' statements. `AccessDeniedHttpException` and `HttpException`.
- I decided to just use the former, since having it in a comment would not look very good while still passing standards for inline comments. Please chime in, if you disagree.
- I decided to just remove the latter, since I (personally) don't see what it adds of value to the user. Since we already show how to throw an AccessDeniedHttpException, I think people would figure these things out?
- Decided to get the logger service namespaced with our custom module (example). This does not relate to coding standards, so if you want me to add another PR for that line (or if you disagree), I am fine with that.
Thoughts?
> Fix coding standards for REST resource generation.

- templates/module/src/interface-entity.php.twig
OK, this change looks a little uglier actually. But it produces better output code, which I think is more important.
If we have the endblock on the next line, it will produce 2 blank lines, and the sniffer will complain.
> Fix coding standards for config entities.

- templates/module/src/Plugin/Rest/Resource/rest.php.twig
The trailing {{ module_name }} should be {{ class_name }} in rest.php.twig.
> Fixes class_name in rest.php.twig @file block.

- README.md
- README.txt
Update instructions in Readme.md obtained of drupalconsole website.
> fixes in Readme.md and Readme.txt

- Test/DataProvider/PluginCKEditorButtonDataProviderTrait.php
- Test/Generator/PluginCKEditorButtonGeneratorTest.php
- config/translations/en/generate.plugin.ckeditorbutton.yml
- src/Command/Generate/PluginCKEditorButtonCommand.php
- src/Generator/PluginCKEditorButtonGenerator.php
- templates/module/src/Plugin/CKEditorPlugin/ckeditorbutton.php.twig
> [generate:plugin:ckeditorbutton] New command

- config/dist/chain/sample.yml
The config provided in the chain example does not create the intended REST states. 
Here is a PR fixing that.
> Make example chain create the wanted states in REST resource.

- src/Helper/Helper.php
This is not needed as both files are within the same namespace.
> [helper] Removed HelperTrait import

- src/Command/Site/ModeCommand.php
Hello,
This PR corrects typo on a path when there's a copy problem on services.yml (I though the command wasn't working because of that, but it was just the message that is wrong).
Regards,
Peekmo
> [site:mode] Invalid message on copy problem

- config/translations/en/module.uninstall.yml
- src/Command/Module/UninstallCommand.php
> Module uninstall force

- config/translations/en/config.import.single.yml
- src/Command/Config/ImportSingleCommand.php
Fixes #2054.
This also added the ability of asking question for the path file.
> Improvement for config:import:single. 

- src/Command/Generate/ModuleCommand.php
> Made the default `yes` for generate:module .module file.

- config/translations/ca/site.import.local.yml
- config/translations/en/site.import.local.yml
- config/translations/es/site.import.local.yml
- config/translations/fr/site.import.local.yml
- config/translations/gu/site.import.local.yml
- config/translations/hi/site.import.local.yml
- config/translations/hu/site.import.local.yml
- config/translations/id/site.import.local.yml
- config/translations/ja/site.import.local.yml
- config/translations/ko/site.import.local.yml
- config/translations/mr/site.import.local.yml
- config/translations/pa/site.import.local.yml
- config/translations/pt_br/site.import.local.yml
- config/translations/ro/site.import.local.yml
- config/translations/ru/site.import.local.yml
- config/translations/tl/site.import.local.yml
- config/translations/vn/site.import.local.yml
- config/translations/zh_hans/site.import.local.yml
- src/Command/Site/ImportLocalCommand.php
Currently it's very easy start using drupal console from scratch, however there's no automated way to start working on existing projects.
With this new command i want to allow users to simply add their existing local sites to the console configuration with a simple command.
Let me know what you think about this, i'm fully open to suggestions.
> [site:import:local] New command for "importing" existing sites.

- config/translations/en/config.override.yml
- src/Command/Config/OverrideCommand.php
See more at https://github.com/hechoendrupal/DrupalConsole/issues/2091
Working in progress
----
However, if we pass a config that is not in the system is going to throw this error. 
> Recoverable fatal error: Argument 2 passed to Drupal\Console\Style\DrupalStyle::choiceNoList() must be of the type array, null given, called in /Users/darrylnorris/Desktop/DrupalConsole/src/Command/Config/OverrideCommand.php on line 58 and defined in Drupal\Console\Style\DrupalStyle->choiceNoList() (line 38 of /Users/darrylnorris/Desktop/DrupalConsole/src/Style/DrupalStyle.php).
There are two options to solve this issue:
- We could not allow overriding any config that is not in the system. And this will throw an error if the config is not in the system.
- Or we can make behave the same way as …
> [config:override] Adding interaction 

- config/translations/en/module.uninstall.yml
- src/Command/Module/UninstallCommand.php
Fixes #2074
A nice improvement that we could do is adding the ability of multiples modules with commas. I personally do not like the behavior from the `module:install` where is going to loop and keep asking for the same question over and over again.
> [module:uninstall] Interact and Question

- config/translations/en/common.yml
- config/translations/en/container-aware.yml
- src/Command/ContainerAwareCommand.php
The container aware command had some hardcore strings in command. Instead of having them on a YML file so it can be translatable.
> [container-aware] Moving strings to yml files so it can be translate.

- src/Application.php
When settings were being checked in Application.php the following error was occuring due to the mismatch in command names.
`[Symfony\Component\Console\Exception\CommandNotFoundException]  
Command "settings:check" is not defined.                        
Did you mean one of these?                                      
settings:set                                                
settings:debug `
> Fix exception when php settings were being checked

- templates/module/src/Form/form-alter.php.twig
- templates/module/src/Form/form-config.php.twig
- templates/module/src/Form/form.php.twig
[https://github.com/hechoendrupal/DrupalConsole/issues/2205](url)
If the title or description captured during the generation process for the form contain any single quotes, then the generated code contains a syntax error.
- drupal generate:form:config
- When asked for title include a ' in your description like: David's module
- When asked for the description include a ' in your description like. This is David's module config form
- Finish generation
- Enable the module containing the form
Escaping title/description in the twig template for form.
> [generate:form:config] Single quote in title or description results in parse error at module install #2205

- src/Application.php
This prevents exception dump
```zsh
sites/drupal/d8/www % drupal
PHP Warning:  preg_match(): No ending delimiter '^' found in /Users/clemens/lib/DrupalConsole/src/Application.php on line 208
PHP Stack trace:
PHP   1. {main}() /Users/clemens/lib/DrupalConsole/bin/drupal:0
PHP   2. require() /Users/clemens/lib/DrupalConsole/bin/drupal:4
PHP   3. Symfony\Component\Console\Application->run() /Users/clemens/lib/DrupalConsole/bin/drupal.php:104
PHP   4. Drupal\Console\Application->doRun() /Users/clemens/lib/DrupalConsole/vendor/symfony/console/Application.php:123
PHP   5. preg_match() /Users/clemens/lib/DrupalConsole/src/Application.php:208
Warning: preg_match(): No ending delimiter '^' found in /Users/clemens/lib/DrupalConsole/src/Application.php on line 208
Call Stack:
0.0001     224048   1. …
```
> Check for empty uri.

- templates/module/src/Entity/entity-content.php.twig
That PR reduce the code generated in <Entity>::baseFieldDefinitions() by calling parent::baseFieldDefinitions().
It also change a little the entity_keys to avoid code duplication.
> Simplify content entity generation.

- config/translations/en/module.uninstall.yml
- src/Command/Module/UninstallCommand.php
the command must execute both things:
1. remove package in composer.json
2. uninstall from Drupal as regular (manual) installed modules
> module:uninstall --composer:  

- templates/module/src/Entity/entity-content.php.twig
Hi!
Currently when we generate a content entity using the command generate:entity:content it is not set to translatable. The problem comes when we have content already created and we need to set our entity as translatable. We can't set it as translatable just adding the properties needed to the annotation of the entity, additionally we have to write a hook_update_n for migrating our entities to the new database structure if we want to have our entity translatable and don't lose data.
As you can imagine, the process is not simple at all for end users, it can be really a problem and you need to have a deep knowledge about the update process. Because of that, I propose to set the entities generated by the console to translatable by default. Then users can configure them within the content …
> Generate Content entities as translatable by default. fix 2354

- templates/module/permissions-entity-content.yml.twig
- templates/module/src/entity-content-route-provider.php.twig
Hi,
This pull request solves the problem with the permissions when a non admin user try to access to the content entity list generated by the command generate:entity:content .
The problem was that the permission "view {{ label|lower }} entities" is not defined at permissions-entity-content.yml.twig that's why an non user can't access to the entity list.
I changed the name of the permission for avoiding to confuse it with the publish and unplish ones, this name structure is the same that Node module does (access content overview).
Thanks!
> #2289 : Fix permission for access to the custom entity content overview.

- config/translations/en/module.download.yml
- config/translations/en/site.new.yml
- config/translations/en/theme.download.yml
- src/Command/Module/DownloadCommand.php
- src/Command/Theme/DownloadCommand.php
- src/EventSubscriber/ShowTipsListener.php
_theme:download --composer_ binds to _module:download --composer_
it downloads the theme well and _Composer_ manages where to put it
also, created a tip
> 'Pass a «true» value to «shellexec_output» key in your config.yml file to see interactively Composer''s output or «false» to hide it'
it appears in _site:new_, _module:download_ & _theme:download_
also removed a lost «`echo`» in _ShowTipsListener.php_
> 2353 theme download

- config/translations/en/generate.form.alter.yml
- src/Command/Generate/FormAlterCommand.php
When we try to execute the command : drupal gfa --module="myroute" --form-id="contact_message_product_information_form" , we get the following error 
Key "class" does not exist as the array is empty in "module/src/Form/form-alter.php.twig" at line 10
I just added the missing keys and now the command is working properly
> Fix issue 2383-Form-alter

- templates/module/links.action-entity-content.yml.twig
- templates/module/src/Entity/entity-content.php.twig
Drupal version 8.1.3
Drupal Console version 1.0.0-beta2
When you generate a content entity with bundles, you get a `Symfony\Component\Routing\Exception\RouteNotFoundException` on entity collection route.
**Reproducing steps:**
`drupal generate:module --module=foo`
Leave options as default.
`drupal generate:entity:content --module=foo --entity-class=Bar`
Leave options as default except for entity have bundles set to yes
When visiting `/admin/structure/bar` you should get the error.
**Proposed solution**
- Add an add-page link in content entity annotations to allow the route provider to create the route
- Prefix the entity `add_form` route name in action links file with `entity` so that the route name matches with the route provider one.
> [generate:entity:content] RouteNotFoundException with bundles

- config/translations/en/generate.entity.content.yml
generate:entity:content command asks for a name for the entity but the request should be for a machine name
> [translation] generate:entity:content should ask for machine name (english)

- Test/DataProvider/EntityContentDataProviderTrait.php
- Test/Generator/EntityContentGeneratorTest.php
- config/translations/ca/generate.entity.content.yml
- config/translations/en/generate.entity.content.yml
- config/translations/es/generate.entity.content.yml
- config/translations/fr/generate.entity.content.yml
- config/translations/gu/generate.entity.content.yml
- config/translations/hi/generate.entity.content.yml
- config/translations/hu/generate.entity.content.yml
- config/translations/id/generate.entity.content.yml
- config/translations/ja/generate.entity.content.yml
- config/translations/ko/generate.entity.content.yml
- config/translations/mr/generate.entity.content.yml
- config/translations/pa/generate.entity.content.yml
- config/translations/pt_br/generate.entity.content.yml
- config/translations/ro/generate.entity.content.yml
- config/translations/ru/generate.entity.content.yml
- config/translations/tl/generate.entity.content.yml
- config/translations/vn/generate.entity.content.yml
- config/translations/zh_hans/generate.entity.content.yml
- config/translations/zh_hant/generate.entity.content.yml
- src/Command/Generate/EntityContentCommand.php
- src/Generator/EntityContentGenerator.php
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/entity-translation-handler.php.twig
This pull request try to solve #2242 
- Added a new option for set the new content entities as translatable or not.
- In case the entity is set as translatable the annotation is updated according to that and a translationHandler class is added. Nothing is done in other case.
```
$ drupal-console generate:entity:content
Enter the module name [block_example]:
> lopd
Enter the class of your new content entity [DefaultEntity]:
> ContentEntity
Enter the name of your new content entity [content_entity]:
> 
Enter the label of your new content entity [Content entity]:
> 
Enter the base-path for the content entity routes [/admin/structure]:
> 
Do you want this (content) entity to have bundles (yes/no) [no]:
> 
Is your entity translatable (yes/no) [yes]:
```
> #2242 [generate:entity:content] Allow option to generate translatable content entities

- config/services/exec.yml
- config/translations/en/exec.yml
- src/Command/Exec/ExecCommand.php
- src/Utils/ShellProcess.php
This command execute an external command, the idea is provide **similar** functionality to `phing`
`drupal exec "ls -al"`
> Add Exec command

- src/Command/Module/DebugCommand.php
drupal module:debug module_name wasn't working because it wasn't find any repo to search the module.
i added `https://packagist.drupal-composer.org/` before the module name in order `drupal console` find it there.
it's working for me now ^^
this PR comes from #2292
> Added Drupal-Packagist repo for searching the module

- config/translations/ca/generate.controller.yml
- config/translations/en/generate.controller.yml
- config/translations/es/generate.controller.yml
- config/translations/fr/generate.controller.yml
- config/translations/gu/generate.controller.yml
- config/translations/hi/generate.controller.yml
- config/translations/hu/generate.controller.yml
- config/translations/id/generate.controller.yml
- config/translations/ja/generate.controller.yml
- config/translations/ko/generate.controller.yml
- config/translations/mr/generate.controller.yml
- config/translations/pa/generate.controller.yml
- config/translations/pt_br/generate.controller.yml
- config/translations/ro/generate.controller.yml
- config/translations/ru/generate.controller.yml
- config/translations/tl/generate.controller.yml
- config/translations/vn/generate.controller.yml
- config/translations/zh_hans/generate.controller.yml
- config/translations/zh_hant/generate.controller.yml
as documented on issue https://github.com/hechoendrupal/DrupalConsole/issues/2025
> Improved instructions at method title prompt

- config/services/migrate.yml
- src/Command/ContainerAwareCommand.php
- src/Command/Migrate/DebugCommand.php
- src/Command/Migrate/ExecuteCommand.php
- src/Command/Migrate/SetupCommand.php
- src/Command/Shared/DatabaseTrait.php
- src/Command/Shared/MigrationTrait.php
List of changes: 
- Now we are using plugins to get a  list of migrations ids 
I removed the method getMigrations() from src/Command/ContainerAwareCommand.php and I moved it to a new Trait called MigrationTraid. 
We load migrations using this:
`$plugin_manager = $this->getDrupalService('plugin.manager.migration');
$all_migrations = $plugin_manager->createInstancesByTag($version_tag);`
- To get those migrations we must to set up the database settings, so I made some changes to command migrate:setup
This command now only load the database configuration  , so I removed the code which generate templates. 
- In order to get the dbTypes now we are calling the function directly from the core with:
`include_once DRUPAL_ROOT . '/core/includes/install.inc';
return drupal_get_database_types();`
- To …
> [migrate:*] Updated commands to process migrations

- config/translations/es/cache.context.debug.yml
- config/translations/es/event.debug.yml
- config/translations/es/exec.yml
- config/translations/es/generate.module.file.yml
- config/translations/es/multisite.new.yml
- src/Command/Update/ExecuteCommand.php
added some yml translation files in spanish
> nuevos ficheros de traducción al español

- src/Command/Config/ExportCommand.php
ArchiveTar takes an argument in the constructor, this is causing warnings and notices during a config export command.
The variable is overwritten soon after in the conditional so is unnecessary.
> [config:export] Fix PHP warnings and notices

- templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
Code was using the old placeholder style (`!size`) instead of the new placeholder format (`@size`).
> Updated t() from !size to @size.

- config/translations/en/common.yml
> #1991 - Alternative exiting of form creation

- templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
*Problem/Motivation*
A generated widget will not reflect basic properties of the field e.g. display label or description.
*How to reproduce*
Run `drupal generate:plugin:fieldwidget`. Subsequent input should not matter in this regard.
*Solution*
`formElement()` accepts an `$element` argument. This contains basic properties such as title, description and whether the value is required.
In the current template this argument is overridden with an empty array. As I see it there is no reason to override the variable.
> [generate:plugin:fieldwidget] Do not override field widget form element

- config/dist/phpcheck.yml
This extension has been removed in PHP7 and the error message is misleading.
> Fix #2130 Do not check for mysql and sqlite3 extension

- src/Command/ServerCommand.php
- src/Command/Shared/ProjectDownloadTrait.php
- src/Zippy/Adapter/TarGzGNUTarForWindowsAdapter.php
- src/Zippy/FileStrategy/TarGzFileForWindowsStrategy.php
In https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/windows.html, 
"Git Bash" is recommended for Windows environment.
But installation with "quick-start" (```drupal chain --file="C:\Users\{user}\.console\chain\quick-start.yml"```) failed because it has some error regarding path style.
this problem is reported at #2214 .
> support Git Bash on windows

- config/translations/en/check.yml
Today i stumpled upon issue #1959 with the missing time zone configuration and at first I thought a drupal configurations is meant because the message came up when I issued drupal config:diff in the terminal. Here is my idea to save other people some time.
> #1959 Show Info that the missing configuration is a php-configuration.

- src/Command/ServerCommand.php
On windows, server command is timeout every 60 seconds.
> prevent timeout of server process on windows

- templates/module/links.menu-entity-config.yml.twig
- templates/module/links.menu-entity-content.yml.twig
This pull request fixes the problem I was having in 
https://github.com/hechoendrupal/DrupalConsole/issues/2634
> [#2634] Ensure link menu definition starts on a new line.

- templates/module/src/Form/form-alter.php.twig
No exist a last close bracket, in form_id validation. execute command with default values.
> Error in: drupal generate:form:alter.

- src/Command/Config/ExportSingleCommand.php
> Fix wrong variable name

- config/services/drupal-console/misc.yml
- src/Command/ContainerParametersCommand.php
Suggested content for console-en / translations / container.parameters.yml:
description: 'Displays current parameters for an application. Internal parameters of Drupal, Console, and the container are excluded for readability.'
> [container:parameters] Issue #2766: add a container:parameters command.

- src/Command/Generate/ModuleCommand.php
Only triggered if --machine-name is used in the module:generate call.
see also #2801 and #2802
> Fix incorrect validation call

- config/services/drupal-console/site.yml
- src/Command/Site/StatisticsCommand.php
fix failing command [site:statistics] when comment module is uninstalled
> [site:statistics] command fails when comment module is uninstalled. Fix #2744

- bin/drupal.php
[Issue](https://github.com/hechoendrupal/DrupalConsole/issues/2785)
Add's a check to the autoload to check whether drupal console is installed globally or within the project itself.
> WIP: Fix to autoload if console is installed globally or within project

- config/services/drupal-console/taxonomy.yml
- src/Command/Taxonomy/DeleteTermCommand.php
Inject and use dependencies in  [taxonomy:term:delete] #2812
> [taxonomy:term:delete] Inject dependencies. (#2812)

- src/Command/Database/DumpCommand.php
- src/Command/Module/InstallCommand.php
PR for #2862
i preferred to use native php functions for gzipping the file rather than using Drupal ArchiveTar class.
i did
``` php
file_put_contents(
$resultFile,
gzencode(
file_get_contents(
$file
)
)
);
```
perhaps you don't like it :upside_down_face:
> added --gz option to database:dump

- templates/module/src/Entity/entity-content.php.twig
In entity-content template ContentEntityBase must be used instead of ContentEntityInterface.
To reproduce:
Just 'drupal generate:entity:content' and choose to NOT enable revision
> [generate:entity:content] The entity-content template must use ContentEntityBase.

- src/Command/Module/DownloadCommand.php
«Please, choose a 'module_name' version» 
instead of 
«Please, choose a… Packagist Drupal version»
> PR for #2845

- src/Command/Module/UninstallCommand.php
Currently if you run module:uninstall with f.e. comment and node, it will print this helpful message:
`[ERROR] Unable to uninstall modules "" because are required by "standard"`
this is because the module variable is null
if fixed to correctly implode the moduleList variable it'll print
`[ERROR] Unable to uninstall modules "comment, node" because are required by "standard, history, taxonomy, standard"`
but `[ERROR] Unable to uninstall modules "comment", "node" because are required by "standard, history, taxonomy, standard"` is better.
> Fix msg for module:uninstall with dependencies.

- templates/module/plugin-annotation-services.yml.twig
When generating a new annotation based plugin type the resulting services.yml looks like this:
```yaml
services:
plugin.manager.sandwich_plugin_manager.processor:
class: Drupal\sandwich\Plugin\SandwichPluginManagerManager
parent: default_plugin_manager
```
Best practices for plugin manager service name are to prefix the service with `plugin.manager.` and then the name of the service. The addition of the `.processor` suffix here is kind of strange.
Contrast this with these definitions for core.services.yml, none of which have the .processor suffix.
```yaml
plugin.manager.entity_reference_selection:
class: Drupal\Core\Entity\EntityReferenceSelection\SelectionPluginManager
parent: default_plugin_manager
plugin.manager.block:
class: Drupal\Core\Block\BlockManager
parent: …
```
> Do not add ".processor" to end of plugin manager service name

- src/Bootstrap/Drupal.php
- PB: it looks like the uri parameter is not taken in account anymore and the multisite doesn't work
- FIX: read the uri option and generate a  symfony request accordingly before initializing the drupal container
> [BUGFIX #2002] uri parameter not used

- Test/Builders/a.php
- Test/Command/Generate/ServiceCommandTest.php
> Fix service command test

- Test/Command/Generate/AuthenticationProviderCommandTest.php
- Test/Command/Generate/CommandCommandTest.php
- Test/Command/Generate/EntityBundleCommandTest.php
- Test/DataProvider/AuthenticationProviderDataProviderTrait.php
- Test/DataProvider/CommandDataProviderTrait.php
- Test/DataProvider/EntityBundleDataProviderTrait.php
- src/Command/Generate/EntityBundleCommand.php
* Rename and move tests classes to match class and package names of its subjects under test.
* This improves the navigation between test and test subject. (ctrl+shift+T in PHPStorm for instance).
* Add keys to the arrays in the data providers traits.
* Adding keys to every data set will improve the error message provided by PHPUnit
- `... with data set "Container aware" ...`
* Adding keys to every element in the data set will explain its content and provide context.
- `'module' => 'foo'` instead of only `'foo'`
> Conventions for Test classes and its Data Providers.

- src/Command/Rest/DisableCommand.php
According to issue https://github.com/hechoendrupal/DrupalConsole/issues/2911
> [rest:disable] Fix rest disable functionality

- src/Command/Update/ExecuteCommand.php
As [discussed in Gitter](https://gitter.im/hechoendrupal/DrupalConsole?at=58216ff378ec59ab05479d07) in the latest rc8 seems like that `drupal update:execute all` is broken.
The reported error is 
> Call to member function getPath() on null in […]src/Command/Update/ExecuteCommand.php on line 187
I believe that the `loadLegacyFile` should be including the current install module, not the parameter as fixed in this PR.
> [update:execute] Require correct '.install' file for each module during updates

- src/Extension/Extension.php
After generate of a entity the templates files should be in MODULENAME/templates not in MODULENAME/src/templates this causes a exception on entity view.
> Fixes wrong template path on generate:entity:content

- templates/module/src/Entity/entity-content.php.twig
If you generate a entity that is not translatable dont define "data_table" annotation because of side effects with views.
See for data_table implementaion @ https://www.drupal.org/node/1498674
> Declare data_table in annotation only if entity is translatable

- config/services/drupal-core/rest.yml
- src/Command/Rest/EnableCommand.php
What I did:
- Did cleanup
- Add serializer format
- Update translation text from "states" to "method" since doesn't make sense to be "states"
for the following reasons
GET, POST, DELETE, PATCH  are NOT states! they are METHODS see: 
- http://www.restapitutorial.com/lessons/httpmethods.html
- https://en.wikipedia.org/wiki/Representational_state_transfer
and also translation in English is:
"REST States to enable for Rest resource:"
which should be "METHODS to enable for Rest resource"
I'll make sure I do PR for sure!!
So the above is the reason why I am changing "states" to "method"
Please this PR is still in PROGRESS so DO NOT merge till I finish it! thanks!
UPDATE!:
Finally fix is already done!!
> [rest:enable] Fix enable rest resource

- composer.json
- src/Command/Chain/ChainCommand.php
I have added some comments in my chain commands but the lines are being interpreted and the comments that have placeholders are being parsed by extractPlaceHolders().
Currently, this is the default behaviour:
Contents of chain-maintenance.yml
```
commands:
- command: site:maintenance
arguments:
mode: '%{{mode|off}}'
```
When I run
`drupal chain --file chain-maintenance.yml`
I get:
>  Enter placeholder value for <comment>mode</comment> [off]:
>  Enter placeholder value for <comment>target</comment> [local]:
When I run the same command passing mode as argument
I get
>  [ERROR] Missing inline placeholder(s) "target"
>  Pass inline placeholders as:
> --placeholder="target:TARGET_VALUE"
So that means, even the comment lines are being parsed.
This is what this pull request is about.
> Commented lines pr

- templates/module/src/entity-content-route-provider.php.twig
getRevisionTranslationRevertRoute() method is included only in content entities when the revisionable entity is marked as translatable.
However, the method is called always when the entity type is marked as revisionable.
This throws the error below:
> Call to undefined method Drupal\ef_system\CompanyHtmlRouteProvider::getRevisionTranslationRevertRoute() in /var/www/drupalvm/web/modules/custom/ef_system/src/CompanyHtmlRouteProvider.php on line 45 #0 /var/www/drupalvm/web/core/lib/Drupal/Core/EventSubscriber/EntityRouteProviderSubscriber.php(47): Drupal\ef_system\CompanyHtmlRouteProvider->getRoutes(Object(Drupal\Core\Entity\ContentEntityType))
That's why I'm proposing here to add an extra check and call that method and create the route only when the entity type is revisonable AND …
> Include TranslationRevertRoute only when content entity is translatable

- src/Command/Router/DebugCommand.php
Requirements are a important part of the route definition. They contain the required permissions to access the route for example (see see system.routing.yml)
> router:debug should dump route requirements

- src/Command/Config/ExportCommand.php
- src/Command/Config/ExportSingleCommand.php
- src/Command/Shared/ExportTrait.php
Added new "remove-config-hash" option to config:export and config:export:single commands.
> New "remove-config-hash" option to config:export and config:expport:single

- templates/module/src/Form/entity.php.twig
- templates/module/src/Plugin/Field/FieldFormatter/imageformatter.php.twig
`\Drupal\Core\Entity\EntityInterface::urlInfo()` is deprecated. Noticed when reviewing generated code.
> [template] Replace deprecated urlInfo() with toUrl()

- src/Command/Multisite/NewCommand.php
Use $this->appRoot, $this->root is empty, which breaks
example.sites.php -file test.
This fixes the issue where `example.sites.php` is not found during  `drupal multisite:new --site-uri=local-2.example.com --copy-install -learning -vvvv local-2.example.com`
> [multisite:new] Use correct  property in example.sites.php search

- src/Command/Database/DatabaseLogBase.php
- src/Command/Database/LogDebugCommand.php
- src/Command/Database/LogPollCommand.php
Updated version of the database poll command. 
Originally in this PR https://github.com/hechoendrupal/DrupalConsole/pull/2529 but i ended up deleting my branch and refactoring everything, so it also needs a new PR because the old one was auto closed :S
- Added database:log:poll command to poll the db for new log messages every 'x' seconds
- Refactored database:log:debug to share a base class with database:log:poll
- Added option to print single database entry as yml or table format
see https://github.com/hechoendrupal/drupal-console-en/pull/51 for strings
> update base class, refactor debug and poll commands

- src/Command/User/PasswordHashCommand.php
Sites may want to replace the default password service (e.g. to use a wrapper around password_hash() and friends).  Typehint the password service as Drupal\Core\Password\PasswordInterface instead of Drupal\Core\Password\PhpassHashedPassword
> [user:password:hash] relax password service typehint

- src/Command/User/PasswordHashCommand.php
Calling the hash() method on the password string, not the password service causes fatal error.
> [user:password:hash] fix typo

- src/Command/Database/DumpCommand.php
drupal help database:dump refers to wrong key when looking for (english) translations. This PR fixes the issue and help displays the correct text instead of wrong key with no translation.
> [database:dump help] Correct keys for translation lookup

- src/Command/Migrate/SetupCommand.php
When the devel's webprofiler submodule is activated, the migre:setup command fails with the following exception:
TypeError: Argument 1 passed to Drupal\Console\Command\Migrate\SetupCommand::__construct() must be an instance of Drupal\Core\State\State, instance of Drupal\webprofiler\State\StateWrapper given in /srv/www/drupal/src/vendor/drupal/console/src/Command/Migrate/SetupCommand.php on line 44 #0 [internal function]: Drupal\Console\Command\Migrate\SetupCommand->__construct(Object(Drupal\webprofiler\State\StateWrapper), Object(Drupal\migrate\Plugin\MigrationPluginManager))
#1 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 /srv/www/drupal/src/vendor/symfony/dependency-injection/ContainerBuilder.php(468): …
> Fix incompatibility between webprofiler module and migrate:setup command

- bin/drupal.php
- src/Command/Generate/ModuleCommand.php
- src/Generator/ModuleGenerator.php
- templates/module/module-twig-template-append.twig
- templates/module/twig-template-file.twig
Added another question that prompts the user if they want to add a default template file and correlating file changes for that file to be recognized.
> Additions to the generate module command

- src/Command/Site/ModeCommand.php
this comes from https://github.com/hechoendrupal/DrupalConsole/pull/2969
it's a fresh and actulized PR for easy merge 😉
> working disable cache page in site:mode dev

- src/Generator/UpdateGenerator.php
Noticed today that when using **drupal generate:update** with no module or install file present; a module file is created rather than *.install.
Modification to generate() function within UpdateGenerator.php to create *.install file as apposed to *.module file. As hook_update_N() should be placed in *.install file by best practice.
> Create x.install file instead of module when using generate:update

- src/Command/Site/InstallCommand.php
Allow user to omit --db-pass -option ie. set an empty password (instead of assuming ‘root’ as password)
> [site:install] Allow empty db password during install

- src/Application.php
- src/Command/Config/ExportSingleCommand.php
- src/Command/Config/ImportSingleCommand.php
* [console] Show error on command registration error.	
* [config:export:single] Multiple fixes and improvements
* [config:import:single] Multiple fixes and improvements
> [config:*:single] Fix config single options

- templates/module/src/Entity/entity-content-views-data.php.twig
When a content entity is generated it currently shows up twice in the "Add view" wizard:
One of the two entries doesn't work correctly, when it is selected it is not possible to select any of the fields on the entity to use in the view.
I had a look and this appears to happen due to an additional base table being declared in `MyEntityViewsData::getViewsData()`. When I delete this section and simply use the default output from the parent class then it works as expected; core seems to handle it fine.
It's not clear to me why this additional base table was added. This was originally added in [Issue #2358493: Integration with Views for entity content generated](https://www.drupal.org/node/2358493) back in 2014 but I could not find a clear explanation of why it was necessary to declare an …
> Remove duplicate declaration of Views base table

- templates/module/entity-content-page.php.twig
The `myentity.page.inc` file which is included when generating a content entity contains two unused use statements. This fails coding standards checks.
> Remove two unused use statements from the template to generate entity.page.inc

- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/Entity/interface-entity-content.php.twig
Related to :
https://github.com/hechoendrupal/DrupalConsole/issues/2996 #2928
(Work in progress)
> Console issue 2996 replace deprecated revision author

- src/Command/Generate/ProfileCommand.php
When passing profile or machine-name on the command line like that:
```
drupal generate:profile --profile=PROFILE --machine-name=MACHINE_NAME
```
drupal console gives an error:
```
Error: Call to undefined method Drupal\Console\Command\Generate\ProfileCommand::validateModuleName()
in Drupal\Console\Command\Generate\ProfileCommand->interact()
(line 234 of .../vendor/drupal/console/src/Command/Generate/ProfileCommand.php).
```
After fixing this another similar error shows up:
```
Error: Call to undefined method Drupal\Console\Command\Generate\ProfileCommand::validateModule()
in Drupal\Console\Command\Generate\ProfileCommand->interact()
(line 253 of .../vendor/drupal/console/src/Command/Generate/ProfileCommand.php).
```
Fix both so that the command line from above works again.
Closes #3035
> [generate:profile] fix passing profile or machine name on the command line

- src/Command/Generate/PluginBlockCommand.php
There are question strings defined (mostly) but they aren't used, unlike in other plugin generation commands, change interact() to use them.
> generate:plugin:block: Use question strings

- src/Command/Config/ValidateCommand.php
- src/Command/Generate/ModuleCommand.php
- config:validate overrides the parent constructor's optional
name argument with a constructor that requires it.
- generate:module requires an argument that is not defined in
the corresponding services file, and should be optional.
> Fix constructor args in two commands (#3041)

- config/services/drupal-console/database.yml
- config/services/drupal-console/generator.yml
- src/Command/Database/AddCommand.php
- src/Generator/DatabaseSettingsGenerator.php
- templates/database/add.php.twig
Adds a database (with hints/defaults) to the site's settings.php - ie for use with migrate etc. see also PR on drupal-console-en coming up next.
> database:add command

- config/services/drupal-console/generate.yml
- config/services/drupal-console/generator.yml
- src/Command/Generate/PluginMigrateSourceCommand.php
- src/Generator/PluginMigrateSourceGenerator.php
- templates/module/src/Plugin/migrate/source/source.php.twig
Currently uses sqlBase so perhaps should consider actually naming it ..:source:sqlbase? (see templates/module/src/Plugin/migrate/source/source.php.twig) english strings PR as well
> generate:plugin:migrate:source

- src/Command/Config/ExportCommand.php
Dear maintainer,
this is a cleanup change, so I did not open an issue for it, but I can do so if it is required.
Thanks,
Antonio
> [config:export] simplify the creation of the target directory

- composer.json
Dear maintainers,
this change is a first step to fix #2584.
I only changed composer.json, I thought I'd let you update the lock file as you have a clearer picture of what all the dependencies should be.
Thanks,
Antonio
> [console] use a more recent alchemy/zipper which fixes GNU tar usage

- src/Application.php
It is important for any program to exit with a non-zero exit code if it
encountered an error.
In Symfony console commands it's common to return with an exit code in
the execute() method of a command. Drupal Console disregards this exit
code in Application::doRun(), making it harder to use Drupal Console
in a scriptable way.
> Allow commands to return an exit code

- src/Command/ServerCommand.php
Hey!
The TTY detection for the server command is a little strange.  It looks like the Process class is capable of doing it's own TTY detection, throwing an exception if you can't use TTY.  I'd propose just using that, and falling back gracefully to printing the output if a TTY session can't be started.
> Use Symfony Process TTY detection, handle no-tty gracefully for server command

- src/Utils/Site.php
Currently the drupal console is unable to find contributed database drivers, as it is not discovering the location where these drivers are supposed to be deployed to.
> Add location for contributed database drivers

- src/Command/Cron/ExecuteCommand.php
See issue https://github.com/hechoendrupal/drupal-console/issues/3126
> cron:execute allow no module name to trigger cron

- src/Command/Update/ExecuteCommand.php
This fixes a few bugs (particularly #3108 and #3137) in applying schema updates and post-update functions. As a result, the update command will also return exit code 1 in case of errors.
> [update:execute] Errors in update code (#3108, #3137)

- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/entity-content-route-provider.php.twig
When using the generated content entity, errors occur, when displaying the revisions tab for that entity type.
```
Symfony\Component\Routing\Exception\RouteNotFoundException: Route "MYENTITY.revision_revert" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 187 of [...]/core/lib/Drupal/Core/Routing/RouteProvider.php).
Symfony\Component\Routing\Exception\RouteNotFoundException: Route "MYENTITY.revision_revert_confirm" does not exist. in Drupal\Core\Routing\RouteProvider->getRouteByName() (line 187 of [...]/core/lib/Drupal/Core/Routing/RouteProvider.php).
```
In addition for _revisionable_ but not _translatable_ entities, no revisions are displayed at all, as _ revision_translation_affected_ is not set. Therefore I guess it is better to remove the …
> Fix revisions tab for generated content entity

- composer.json
This is a simple composer version syntax error that was introduced in https://github.com/hechoendrupal/drupal-console/commit/db1d0868 with no context. The or operator is || not |. See https://getcomposer.org/doc/articles/versions.md
My project already pulls in psy/psysh at version 0.8.1. Drupal/console tries to resolve an unknown version and fails verbosely:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- drupal/console 1.0.0-rc15 requires doctrine/collections 1.3.0 -> satisfiable by doctrine/collections[v1.3.0].
- Conclusion: don't install doctrine/collections v1.3.0
- Conclusion: don't install psy/psysh v0.8.0
- drupal/console 1.0.0-rc13 requires psy/psysh 0.6|0.8 -> satisfiable by psy/psysh[v0.6.0, v0.8.0].
- drupal/console 1.0.0-rc14 requires …
```
> [composer] Fix psy/psysh version dependency

- src/Command/Shared/ExtensionTrait.php
There is a bug inside the ExtensionTrait which is only used by the generate:command command right now. It calls ExtensionManager::getList() without an argument, resulting in an `ArgumentCountError: Too few arguments to function Drupal\Console\Extension\Manager::getList()`.
This pull request adds a parameter to the function call. Alternatively the function could provide a default parameter.
Issue: https://github.com/hechoendrupal/drupal-console/issues/3209
> [generate:command] Add required argument to ExtensionManager::getList()

- Test/Generator/ProfileGeneratorTest.php
- config/services/drupal-console/generate.yml
- src/Command/Generate/ModuleCommand.php
- src/Command/Generate/ProfileCommand.php
- src/Extension/Manager.php
- src/Generator/ProfileGenerator.php
- src/Utils/Validator.php
- templates/profile/info.yml.twig
- uninstall.services.yml
Refactor `checkDependencies()` first and then finally add the `--themes` option as per #3092.
@jmolivas this will require some changes in console-en:
* Remove `commands.generate.module.warnings.module-unavailable`
* Remove `commands.generate.profile.warnings.module-unavailable`
* Add `validator.warnings.extension-unavailable`
* Add `commands.generate.profile.options.themes`
Will you do that?
Thanks,
Antonio
P.S. BTW, with vanilla 1.0.0-rc16 I was getting this error:
```
TypeError: Argument 6 passed to Drupal\Console\Command\Generate\ModuleCommand::__construct()
must be an instance of GuzzleHttp\Client, none given in
.../vendor/drupal/console/src/Command/Generate/ModuleCommand.php on line 84
```
However after applying this series the error is gone because `ModuleCommand` does not use …
> [generate:profile] add option to specify enabled themes

- config/services/drupal-console/config.yml
- src/Command/Config/ExportCommand.php
In particular, this includes the language.* collections provided by the config_translation module, and fixes a bug wherein config:export followed by config:import will delete translations.
> [config:export] Export all config collections (#3182)

- config/services/drupal-console/module.yml
- src/Command/Module/UninstallCommand.php
- When you use "mou" without specifying tha name of the module, the command call modulesUninstallQuestion to load the list of installed module.
- modulesUninstallQuestion method in turn load the list using the extensionManager
- the extensionManager is not injected and declared in the UninstallCommand so we got a null reference exception.
**To reproduce just run "drupal mou" without specifying tha name of the module**
> Added the extensionManager nedded by mou when no module is specified.

- templates/module/Tests/Controller/controller.php.twig
- templates/module/module.views.inc.twig
- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/Form/entity-content-revision-delete.php.twig
- templates/module/src/Entity/Form/entity-content-revision-revert-translation.php.twig
- templates/module/src/Entity/Form/entity-content-revision-revert.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Entity/entity-content-with-bundle.theme_hook_suggestions.php.twig
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/Entity/entity-content.theme.php.twig
- templates/module/src/entity-storage.php.twig
- templates/module/src/listbuilder-entity-content.php.twig
- templates/module/src/yaml-plugin-manager.php.twig
Pull request for #3229 
Currently the templates in Drupal Console use a combination of the short and long array syntax. Sometimes, different syntaxes are even used in the same file. For consistency, one syntax should be used across all templates. 
Short syntax makes the most sense as the Drupal core contributors have already decided to switch to short syntax for their coding standards and, as of 8.3, all of core's code has been switched to the short syntax: https://www.drupal.org/node/2776975
> [template] Use short array syntax in all templates

- uninstall.services.yml
The http_client service is missing, so the site:install command doen't work
> [site:install] Register missing service

- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/Entity/interface-entity-content.php.twig
Currently when a content entity is generated that supports bundles, this piece of code is generated in it:
```
/**
* {@inheritdoc}
*/
public function getType() {
return $this->bundle();
}
```
This getter is duplicating `EntityInterface::bundle()` which is the standard way of getting the bundle from any entity.
Having this `getType()` available only on entities generated by Drupal Console is confusing, since it is missing from core entities. It also doesn't serve any purpose, it is just duplicating existing functionality.
> Remove duplicated getType() from generated content entities

- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/entity-content.php.twig
Currently when generating revisionable content entities we are duplicating a number of methods from `RevisionableContentEntityBase`. This class provides the `RevisionLogEntityTrait` which already contains the following methods so we do not need to duplicate them:
* `getRevisionCreationTime()`
* `setRevisionCreationTime()`
* `getRevisionUser()`
* `setRevisionUser()`
* `getRevisionUserId()`
* `setRevisionUserId()`
Additionally, it already defines base field definitions regarding which are duplicated by us but named differently. This causes duplicate field definitions to be used for these entities:
* `revision_created` (duplicated as `revision_timestamp`)
* `revision_user` (duplicated as `revision_uid`)
It looks like our current implementation is based on that of the `Node` entity which …
> Leverage methods and base field definitions from RevisionLogEntityTrait

- templates/module/src/Command/command.php.twig
- templates/module/src/Controller/controller.php.twig
- templates/module/src/Form/form-config.php.twig
- templates/module/src/Form/form.php.twig
- templates/module/src/Plugin/Block/block.php.twig
- templates/module/src/Plugin/Condition/condition.php.twig
- templates/module/src/Plugin/Field/FieldFormatter/imageformatter.php.twig
- templates/module/src/Plugin/Mail/mail.php.twig
- templates/module/src/Plugin/Rest/Resource/rest.php.twig
- templates/module/src/Plugin/skeleton.php.twig
- templates/module/src/TwigExtension/twig-extension.php.twig
- templates/module/src/cache-context.php.twig
- templates/module/src/event-subscriber.php.twig
- templates/module/src/plugin-type-annotation-manager.php.twig
- templates/module/src/service.php.twig
- templates/module/src/yaml-plugin-manager.php.twig
When generating classes the documentation of the constructors is often missing or not according to documentation standards. The most typical phrase that is used in core is:
```
/**
* Constructs an ImageFormatter object.
*/
```
but since we have to use either 'a' or 'an' depending on whether the class name starts with a vowel, I have opted for the following wording to avoid complexity:
```
/**
* Constructs a new ImageFormatter object.
*/
```
This will be grammatically correct regardless of the naming of the class.
> Improve docblocks for generated constructors

- src/Command/Shared/FormTrait.php
When generating a form the resulting code is formatted with the short array syntax everywhere, but the options for a `select` form field are still using the old syntax:
```
$form['category'] = [
'#type' => 'select',
'#title' => $this->t('Category'),
'#options' => array('Technical problem / bug report' => $this->t('Technical problem / bug report')),
'#size' => 5,
];
```
This PR ensures that short array syntax is also used for the select options.
> Use short array syntax for generated options

- templates/module/src/Plugin/migrate/process/process.php.twig
I used `generate:plugin:migrate:process` to create a migration process plugin the other day, and my plugin was never called. Comparing with other migration process plugins, I saw that the annotation should be `@MigrateProcessPlugin` instead of `@MigrateProcess`. Making this change in my generated code made my plugin start working.
> Use @MigrateProcessPlugin in generate:plugin:migrate:process command

- src/Generator/ModuleGenerator.php
- templates/module/src/Tests/load-test.php.twig
Hi! 
I owe you this for a few months now, sorry! 
Ok,   WebTestBase will be deprecated in the following months. 
https://www.drupal.org/node/2847678
https://www.drupal.org/node/2735005
https://www.drupal.org/node/2851541
Let's help with this change making the DrupalConsole use BTB instead of WTB for any  new generated module. 
Regards.
> Use BTB instead of WTB

- bin/drupal.php
- src/Application.php
With this commit, drupal console will attempt to fetch and use a $launcherVersion variable. This commit needs another commit within drupal-console-launcher in which I add this variable to the global scope. 
After this, drupal console will be able to print the launcher's version, which looks like:
This adresses issue: hechoendrupal/drupal-console#3164
> Print launcher version, addresses hechoendrupal/drupal-console#3164

- config/services/drupal-console/config.yml
- src/Command/Config/ExportSingleCommand.php
After a bit of digging around, it seems that `ExportSingleCommand` was missing the extension manager. This made it impossible for `config:export:single` to export to extensions and failed. Fixes hechoendrupal/drupal-console#3305
> Fixes issue hechoendrupal/drupal#3305, adding missing extension_manager

- templates/module/src/Entity/entity.php.twig
This is a patch for #3129.
This allows content entities with bundles to be exposed through the core REST API without throwing errors of the form: 
```
Route entity.{{entityBundleType}}.canonical does not exist.
```
Steps to reproduce & fix manually have been well described by @tahirm in the linked issue, so I won't re-explain them here.
This patch adds a default 'view_builder' to all config entity definitions. It uses the Core `Drupal\Core\Entity\EntityViewBuilder` & doesn't bother defining a custom extension class in the same way as, for example, the 'list_builder': `Drupal\{{ module }}\{{ entity_class }}ListBuilder` as I haven't come across a use case for this level of flexibility yet. 
I checked Core to see where it extends `EntityViewBuilder` rather than using it directly and found of …
> [generate:entity:content] Add 'view_builder' to config entity annotation template. Fix #3129.

- src/Command/Generate/ThemeCommand.php
Hi there,
While generating a theme; the machine name question is using the wrong prompt.
How to reproduce:
- Run `drupal generate:theme`
- In the machine name prompt; it says: "Enter the module machine name"; it should say "Enter the theme machine name"
This PR fixes it.
> Generate theme command should use right machine name question string.

- templates/module/src/entity-content-route-provider.php.twig
`@use` statements are part of documentation and are shown in rendered documentation. They should use fully qualified namespaces. This also ensures that the developer can navigate to the classes in their IDE.
> Use fully qualified namespace for @use statements

- src/Utils/Create/TermData.php
- src/Utils/Create/VocabularyData.php
When using drupal console to create Vocabularies or Terms, the creation of the "description" field was missing an argument in the `getRandom()->sentences()` call.  This caused the following error:
```
ArgumentCountError: Too few arguments to function Drupal\Component\Utility\Random::sentences(),
0 passed in /vendor/drupal/console/src/Utils/Create/TermData.php on line 69 and at least 1 
expected in Drupal\Component\Utility\Random->sentences() (line 192 of 
/core/lib/Drupal/Component/Utility/Random.php).
```
Solution was to supply the value provided by the user (`$nameWords`) to the function.
Test using:  
`drupal create:vocabularies --limit=5 --name-words=5` or 
`drupal create:terms --limit=5 --name-words=5` and selecting a vocab to use.
> [create:vocabularies] Add missing arguments to empty method call. Resolves #3271.

- templates/module/src/entity-content-route-provider.php.twig
- templates/module/src/entity-route-provider.php.twig
When generating an entity we were providing the collection route in the `HtmlRouteProvider` but this is no longer necessary since core now provides the route. This was added in Drupal 8.2.0 in [Issue #2767853 by tstoeckler: Provide a route for collections of entities](https://www.drupal.org/node/2767853).
> Collection routes are provided by core

- templates/module/src/Authentication/Provider/authentication-provider.php.twig
- templates/module/src/Command/command.php.twig
- templates/module/src/Controller/controller.php.twig
- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/Form/entity-settings.php.twig
- templates/module/src/Form/entity.php.twig
- templates/module/src/Form/form-config.php.twig
- templates/module/src/Form/form.php.twig
- templates/module/src/Routing/route-subscriber.php.twig
- templates/module/src/TwigExtension/twig-extension.php.twig
- templates/module/src/cache-context.php.twig
- templates/module/src/event-subscriber.php.twig
- templates/module/src/service-interface.php.twig
- templates/module/src/service.php.twig
Many of the classes are generated with an `@package` declaration. This is a standard from PhpDoc and is adopted by other popular CMS's like Wordpress but not by Drupal. It is not defined in the Drupal coding standards, and is not used by Drupal core and contrib modules. This information duplicates the namespace declaration, and is completely useless.
This probably found its way into Drupal Console because it is added to class docblocks automatically by PHPStorm.
> Remove @package declarations from generated code

- templates/module/links.action-entity-content.yml.twig
- templates/module/links.action-entity.yml.twig
This is a really minor fix. When specifying routes in YAML files it is not necessary to quote them, since they are resolved to route names, and not raw strings. In almost all of our generated code this is handled correctly, save for two instances when generating action links.
> Quoting route names is not necessary

- src/Command/Theme/InstallCommand.php
- src/Command/Theme/UninstallCommand.php
Improved UX to end the process to include themes to be installed , accepting an empty value as end of the process.
> Fix show themes on theme:install command

- templates/module/src/Entity/entity-content.php.twig
When creating a content entity with revisions enabled but translation disabled, the revision_revert route is not correctly registered.
> [generate:entity:content] Fix revision revert path for untranslatable content

- src/Command/Config/DiffCommand.php
This fixes a bug when passing the directory name argument. Now you can pass rather name / path and it will work.
> [config:diff]:fix bug with directory parameter. (#3373)

- config/services/theme.yml
- src/Command/Theme/PathCommand.php
Related to https://github.com/hechoendrupal/drupal-console/issues/3420
> Updated theme:path command.

- src/Command/Module/InstallDependencyCommand.php
I'm getting a Drupal Console error in my project b/c I'm extending the Drupal "ModuleInstaller" class. My code is then passing in my overridden class via services to Drupal Console. I'm not 100% sure this is right, but this feels like it should be accepting the ModuleInstallerInterface instead of just ModuleInstaller. I'm not that familiar with "ProxyClass"es which is what I'm removing, so I'm not confident this is definitely correct. Please advise if you don't think this is an appropriate bugfix.
* Fixed comment styles.
* Added `@param` to constructor comment.
> Allow inherited ModuleInstaller classes to InstallDependencyCommand.

- config/services/cache.yml
- src/Command/Cache/TagInvalidateCommand.php
This is a command for accessing Drupal's cache tag invalidator, which allows clearing caches more specifically than complete deletion, if you know what tags a cache entry is dependent on.
For example, when you're debugging a view, you can invalidate all related cache entries with `drupal cache:tag:invalidate config:views.view.frontpage` without having to actually trigger the view's save operation.
> Add cache:tag:invalidate command.

- composer.json
Drupal 8.4 updates Symfony component requirements to ~3.2, so will conflict with the current ~2.8 requirement.
The following PRs will also be needed:
- hechoendrupal/drupal-console-core#209
- hechoendrupal/drupal-console-extend-plugin#16
Drupal 8.3 projects will continue to install Symfony 2.8 components where they are requirements of both drupal/core and drupal/console due to Drupal 8.3's constraint of ~2.8, but components that are only requirements of drupal/console may be updated to 3.x versions. This shouldn't be a problem as long as drupal/console doesn't use any deprecated features in those 2.8 components.
Fixes #3353, Fixes #3317, Fixes #3293
> Update Symfony component requirements to allow 3.0+

- src/Command/Config/ExportCommand.php
When I added the code for exporting config translations in #3182 / #3185, I forgot some `mkdir` calls. ;) So translations are only exported if the language folders already exist, but not when you're exporting for the first time or after creating a new language. (Tar mode is unaffected)
> [config:export] Create paths when exporting collections.

- config/services/cron.yml
- src/Command/Cron/ExecuteCommand.php
Fix #3480
Wiping cache manually can kill site performance so forcing it during an
operation that will run very often on most sites could be very damaging.
If a user _needs_ to clear caches at set intervals they can still do so using
the explicit cache commands.
> Don't wipe cache during cron run

- src/Command/Update/EntitiesCommand.php
There are other approaches here, but this is the most straightforward. Initially I was using `Error::renderExceptionSafe` which will render the exception into a string, but it contains html markup which doesn't play nice with console. The markup can then be passed to `Drupal\Component\Render\PlainTextOutput::renderFromHtml` which will strip the tags. But ultimately it's just a round about way to accomplish what I have here. 
`_drupal_log_exception` uses `strtr` so I took inspiration from there. If there is a more "drupal" way to render the exception contents into a plaintext string then that might be better.
> Fix #3503: prints exception variable contents

- src/Command/User/LoginUrlCommand.php
When creating a one time user login link a reset password page is shown with a "login" button to actually login. This change skips that page and just logins directly into the user account.
> Skip the reset password page and just login.

- src/Command/Update/ExecuteCommand.php
A recent change to the update:execute command has made me a sad panda. As of 1.0.2, if there are no pending updates, an error is output and 1 is returned. This broke our Travis CI builds over at acquia/lightning: https://travis-ci.org/acquia/lightning/jobs/272902792
I discussed this problem briefly with @jmolivas on Slack and he said it should warn, not error, and return 0.
> [update:execute] Warn and return 0 if there are no pending updates

- src/Command/Module/UninstallCommand.php
Drupal core #1356276 allows for profiles to be set as a parent profile and for child profiles to inherit from parents. This allows for more than one profile to be installed on a site.
Drupal (and Drush and Drupal Console) has always made exceptions for dependencies of Profiles in that you can actually uninstall dependencies of Profiles without uninstalling the Profile itself. This patch makes the same exception for parent profiles. Or rather, adds all profiles to a list of dependents to exclude instead of just the active/last profile.
It includes a check to see if the patch has been applied to core and works around it if not.
> Allow dependencies of parent profiles to be uninstalled

- templates/module/permissions-entity-content.yml.twig
If I understand things correctly, access to content entity listings/collection used to be provided by the generated entity, but was recently [passed off to core](https://github.com/hechoendrupal/drupal-console/pull/3344). This means that unless the route provider is modified after generation, it's the *administer foo entities* permission that opens the door, not *access foo overview*.
If I've gotten this right - I'm a relative newb to entity building in D8 - it's probably confusing to keep the latter permission lying around.
> [generate:entity:content] Omit 'access /entity type/ overview' permission since it does nothing.

- src/Command/Update/ExecuteCommand.php
If this isn't done, Drupal UI will continue to report that db updates are pending. 
Note, I considered placing this outside of the foreach calls and recording all post updates at once; however that would cause problems if one failed but not the others.
> Properly record ran post_update functions.

- templates/module/src/Entity/interface-entity-content.php.twig
`ContentEntityInterface` does extend `RevisionableInterface`, but also offers knowledge of basic functions such as `id()`, `save()` etc. 
Fixes #3554
> Always extend ContentEntityInterface in interface of new content entity

- src/Bootstrap/AddServicesCompilerPass.php
- src/Bootstrap/Drupal.php
- src/Bootstrap/DrupalKernel.php
- src/Extension/Manager.php
Hi @jmolivas - @enzolutions, at Bluespark we have a project based on Drupal 8.3.7 and Drupal Console 1.0.0-beta4 that tried to upgrade to Drupal Console 1.0.2 but this caused a lot of fatal errors in our custom implementations of commands. I researched a bit of the existing issues and found that our error was very similar than https://github.com/hechoendrupal/drupal-console/issues/3091 so tried the workaround detailed on that issue to avoid usage of session but we found another fatal error that I reported at https://github.com/hechoendrupal/drupal-console/issues/3553
I tried to compare what have changed between the two versions to identify why this erros was not experimented in previous Drupal Console version and found that the main reason is the handle of the "/" default request which …
> Avoid run of Request handle() and use of container at compiler pass to fix issues 3091 and 3553

- config/services/rest.yml
- services.yml
- src/Command/Rest/EnableCommand.php
- src/Command/Shared/RestTrait.php
- src/Utils/Create/Base.php
- src/Utils/Create/CommentData.php
- src/Utils/Create/NodeData.php
- src/Utils/Create/RoleData.php
- src/Utils/Create/TermData.php
- src/Utils/Create/UserData.php
- src/Utils/Create/VocabularyData.php
Since we are moving DrupalConsole services loading from `AddServicesCompilerPass`  to `DrupalKernel` class. Usage of Expression Language in service definition is no longer supported.
Error with current code-base.
> [console] Remove usage of expression builder on services registration.

- templates/module/src/Entity/entity-content.php.twig
From issue #3556:
> After Drupal update to 8.4, when trying to delete a revisionable entity created by drupal console the following exception is thrown:
> "Drupal\Core\Entity\EntityStorageException: Some mandatory parameters are missing ("console_entity_test_revision") to generate a URL for route "entity.console_entity_test.revision_revert". in Drupal\Core\Entity\Sql\SqlContentEntityStorage->delete() (line 753 of /var/www/html/web/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php)"
The issue was also reported (and closed) on drupal.org [0].
I just made a patch with the suggested code on both issues.
[0] https://www.drupal.org/project/drupal/issues/2919327
> FIX #3556: Add urlRouteParameters function to the content entity class

- src/Command/Generate/BreakPointCommand.php
- src/Generator/BreakPointGenerator.php
- Order use statements alphabetically.
- Remove unused variables for drupal root.
- Add comment for the class.
- Rename base_theme to theme to be consistent with the option name.
- Fix coding issues
> [generate:breakpoint] Fix coding issue in BreakPointCommand class.

- src/Command/Create/CommentsCommand.php
- src/Utils/Create/CommentData.php
- Add validation of node id.
- Fix code structure.
- Replace the wrong method getTitle with getSubject.
- Order use statements alphabetically
> [create:comments] Add validation of node id. Fix code structure. Replace the wrong method

- src/Command/Theme/InstallCommand.php
- src/Command/Theme/UninstallCommand.php
1) Remove the code, which was copied from ThemeController.php of the Drupal for both **Install** and **Uninstall** commands
2) Update the message for Install command, when some dependencies are not met
> [theme:*] Remove Drupal core code drupal_set_message.

- templates/module/services.yml.twig
Fix coding standards for https://github.com/hechoendrupal/drupal-console/issues/2166
> Fix cs for AuthenticationProviderCommand

- config/services/generate.yml
- config/services/generator.yml
- src/Command/Generate/PluginMigrateDataParserCommand.php
- src/Generator/PluginMigrateDataParserGenerator.php
- templates/module/src/Plugin/migrate_plus/data_parser/data_parser.php.twig
> [generate:plugin:migrate:dataparser] Add new command for generating data parser plugin for migration. Fix #3773

- templates/module/post-update.php.twig
- templates/module/src/Entity/Form/entity-content-revision-delete.php.twig
- templates/module/src/Entity/Form/entity-content-revision-revert.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Form/entity-delete.php.twig
- templates/module/src/Form/entity.php.twig
- templates/module/src/Form/form-alter.php.twig
- templates/module/src/Form/form.php.twig
- templates/module/src/cache-context.php.twig
- templates/module/src/event-subscriber.php.twig
- templates/module/update.php.twig
drupal_set_message is marked as deprecated and will be removed in drupal 9.
We should use best practices in the templates and fix deprecation issues as fast as possible to keep the effort needed to port this project to drupal 9 minimal.
> [template] Replace deprecated drupal_set_message

- src/Command/Site/InstallCommand.php
This should address the issue mentioned in #3930 
Instead of implicit type casting by means of the `!` operator we check if the value is set but empty (no action) or not set (ask)
> Ask for db prefix only if it is not explicitly set (#3930)

- src/Command/Debug/EntityCommand.php
- src/Command/Entity/DeleteCommand.php
- src/Command/Generate/PluginConditionCommand.php
Changes the type signatures for a few classes to use interfaces instead of classes.
Associated issue: https://github.com/hechoendrupal/drupal-console/issues/3919
> Changes constructor type signatures (#3919)

- templates/module/src/event-subscriber.php.twig
This PR corrects the coding standards of the EventSubscriber template file.
> FIX #3983: Correct coding standards for EventSubscriber class

- config/services/config.yml
- src/Command/Config/ExportParagraphTypeCommand.php
Added Paragraph type export to export Paragraph type's fields with following command:
drupal config:export:paragraph:type
(Translation in separate pull request on drupal-console-en repository)
> Added Paragraph type export command

- src/Generator/ModuleGenerator.php
With unescaped quotes in the module filename - for example, caused by:
```drupal generate:module
// Welcome to the Drupal module generator
Enter the new module name:
> test's this```
You get:
```
drupal generate:module
In InfoParserDynamic.php line 25:
Unable to parse modules/custom/test_s_this/test_s_this.info.yml Unexpected characters near "s this'" at line 1 (near "name: 'test's this'").
```
> Escape single quotes in .info.ym file generation for generate:module cmd

- src/Command/Database/ClientCommand.php
- src/Command/Database/ConnectCommand.php
- src/Command/Database/DumpCommand.php
- src/Command/Database/QueryCommand.php
- src/Command/Database/RestoreCommand.php
- src/Command/Debug/DatabaseTableCommand.php
- src/Command/Module/DownloadCommand.php
- src/Command/Module/InstallCommand.php
- src/Command/Module/UpdateCommand.php
- src/Command/Shared/ConnectTrait.php
1) Add target argument to address specific db.
2) Add escape of command line parameters where it is necessary.
3) Replace double quotes with single quotes.
4) Improve the code standards
> 3888 database dump escape

- src/Generator/FormGenerator.php
- templates/module/routing-form.yml.twig
- templates/module/src/Form/form.php.twig
Make the generated code comply with Coding Standards
How to test:
- Generate module named "mymodule"
- Generate form with this command: `drupal generate:form  --module="mymodule" --class="DefaultForm" --form-id="default_form" --services='current_user' --config-file --inputs='"name":"text_field", "type":"textfield", "label":"text field", "options":"", "description":"", "maxlength":"64", "size":"64", "default_value":"", "weight":"0", "fieldset":""' --path="/mymodule/form/default" --learning --uri="http://default" --no-interaction`
- Evaluate coding standards (ex. `phpcs --standard=Drupal web/modules/custom/mymodule/*`)
- It should pass
> Fix coding standards for generate:form command.

- config/services/generate.yml
- config/services/generator.yml
- src/Command/Generate/PluginQueueWorkerCommand.php
- src/Generator/PluginQueueWorkerGenerator.php
- templates/base/class.php.twig
- templates/module/src/Plugin/QueueWorker/queue_worker.php.twig
Create new command to generate a Queueworker skeleton.
Added doc comment to the base class, optional.
I generate a new Queueworker in a existing module using `drupal generate:plugin:queue`.
Drupal version - 8.6.1
drupal/console 1.8.0 The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.
drupal/console-core 1.8.0 Drupal Console Core
drupal/console-en 1.8.0 Drupal Console English Language
drupal/console-extend-plugin 0.9.2 Drupal Console Extend Plugin
Console Launcher version - 1.8.0
Translation issue: https://github.com/hechoendrupal/drupal-console-en/pull/215
> [generate:plugin:queue] Create new command to generate QueueWorker

- config/services/database.yml
- src/Command/Database/DropCommand.php
1) Added support of any database and not only default one
2) Add target, so we can access any db from settings.php
> Add support of additional database from settings for drop db command

- composer.json
This addresses the following issue: #3845 
Unless there was a reason to lock to a specific version, then ignore.
> allow alchemy/zippy version to go above 0.4.3

- composer.json
- src/Command/Update/ExecuteCommand.php
We can have trailing postUpdates to run or entities update without having any module update.
This pr try to fix that
> [update:execute] run trailing post updates if there is no updates

- src/Command/Debug/UpdateCommand.php
- src/Command/Shared/UpdateTrait.php
- src/Command/Update/ExecuteCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4020.
This Pr show the updates available and the post update, before to the execution. And now we must to confirm the execution
> 4020 fix update execute command

- src/Command/Generate/PluginSkeletonCommand.php
- src/Generator/PluginSkeletonGenerator.php
- templates/module/src/Plugin/skeleton.php.twig
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3993
> [generate:plugin:skeleton] Fixed namespace

- src/Command/Generate/AjaxCommand.php
- src/Command/Generate/AuthenticationProviderCommand.php
- src/Command/Generate/CacheContextCommand.php
- src/Command/Generate/CommandCommand.php
- src/Command/Generate/ControllerCommand.php
- src/Command/Generate/EntityBundleCommand.php
- src/Command/Generate/EventSubscriberCommand.php
- src/Command/Generate/FormAlterCommand.php
- src/Command/Generate/FormCommand.php
- src/Command/Generate/PluginBlockCommand.php
- src/Command/Generate/PluginMailCommand.php
- src/Command/Generate/PluginRulesActionCommand.php
- src/Command/Generate/PluginRulesConditionCommand.php
- src/Command/Generate/PluginRulesDataprocessorCommand.php
- src/Command/Generate/PluginTypeAnnotationCommand.php
- src/Command/Generate/PluginTypeYamlCommand.php
- src/Command/Generate/TwigExtensionCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/4033
Commands updated:
```
generate:twig:extension
generate:cache:context
generate:command
generate:controller
generate:event:subscriber
generate:form
generate:plugin:block
generate:plugin:mail
```
> [console] Added the ContainerAwareCommand extension

- config/services/database.yml
- config/services/generator.yml
- src/Generator/DatabaseSettingsGenerator.php
- uninstall.services.yml
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3097 and took the solution of running database commands and using them without drupal bootstap
Exposed commands:
```
database:add
database:connect
database:query
```
> [database] Run database commands without Drupal bootstrap

- config/services/debug.yml
- config/services/rest.yml
- src/Command/Debug/RestCommand.php
- src/Command/Generate/PluginRestResourceCommand.php
- src/Command/Rest/DisableCommand.php
- src/Command/Rest/EnableCommand.php
- src/Command/Shared/RestTrait.php
- templates/module/src/Plugin/Rest/Resource/rest.php.twig
This PR fixed the template to generate a plugin:rest:resource functional
Affected commands:
```
generate:plugin:rest:resource
debug:rest
rest:enable
rest:disable
```
> Update rest resource command

- src/Command/Multisite/NewCommand.php
- src/Utils/Validator.php
- uninstall.services.yml
This PR validates the uri name to be able to implement this PR https://github.com/hechoendrupal/drupal-console/pull/3871
Now we can run `drupal multisite:new example example.com` this creates a folder called `example` but the multisite is called `example.com`
The reference in sites.php
```
$sites['example.com'] = 'example';
```
> [multisite:new] Validated uri name

- src/Command/Multisite/NewCommand.php
When running the `drupal multisite:new ` the second argument `uri` is never used and the `directory` argument is used in its place making it impossible to take full advantage of all the functionality in the `sites.php` file that this command writes to
run `Drupal multisite:new new-site http://new-site.example.com`
In `sites.php` you will see `$sites['new-site'] = 'new-site';`
When the final result should actually be `$sites['http://new-site.example.com'] = 'new-site';`
The solution in this PR fixes the issues
> [multisite:new] fix so that multi site command uses uri argument

- src/Command/Site/InstallCommand.php
The Pr allow install a site using a db url, avoiding using the options.
Example
```
drupal site:install  standard mysql://dbUser:dbPass@dbHost/dbName --no-interaction
```
> [site:install] Implement db_url to install

- src/Command/Site/StatusCommand.php
Use Drupal's method to determine the db connection's URL, instead of own logic. Hide the password if existing, for security reasons.
> [site:status] Use Database::getConnectionInfoAsUrl to get the db URL

- src/Command/Config/ImportCommand.php
Reason for this pull request:
I'm trying to use the drupal/config_ignore module, which in turn relies on drupal/config_filter module to maintain a separate local dev/staging/prod configuration. Config_ignore has changed how it works internally and relies on config_filter to provide the filtering mechanism. config_filter in turn decorates the config.storage.staging/sync service in order to inject it's own FilteredStorage class to handle the filtering. But the current Drupal console class ```src/Command/Config/ImportCommand.php``` creates a FileStorage instance directly inside it's execute command, instead of relying on the instance returned from ```\Drupal::service('config.storage.sync')```. Thus the decorated class is never made available to the import command and the import filtering …
> config:import changed to support config.storage.sync service for default instance 

- src/Command/Site/InstallCommand.php
Looking at the newly introduced --db-url argument for site:install, I believe there's room for some improvements.
If --db-url is specified **and valid**, there is no purpose to go through the other options. We can just install based on that.
Here's my suggested changes  - **not for merging yet** but rather for sharing with the community - I am new to Drupal console contribution so please bear with me.
My goal: allow `site:install` to run on ANY database driver (also contributed), as long as it complies to the Drupal API for `Database::convertDbUrlToConnectionInfo` and `Database::getConnectionInfoAsUrl`.
> [site:install] Improve support of --db-url

- src/Command/Update/ExecuteCommand.php
See Issue #3929
drupal updb does not support batch updates. This has made updating from 8.6.x - 8.7.0 impossible as several of the post_update functions require batch processing.
Details of how to reproduce can be found on issue #3929 
Update ExecuteCommand::executeUpdate() to loop over the update function until it is completed. Provide helpful feedback to the user throughout this process.
I've added a `do { } while() ` loop into executeUpdate to ensure that the function get's run the correct number of time.
A default message of 'Processed x%' is printed as information and indented to make clear that it relates to the function above.
> [update:execute] Support batch updates and post update functions

- src/Command/Update/ExecuteCommand.php
This PR fix the table to show updates
> [update:execute] Fixed update table

- src/Command/Site/InstallCommand.php
1. If Drupal is already installed, and --force is not set, there's no point to continue an interactive install that will lead to an error anyway. Exit early.
2. The Drupal installer, when erroring out, returns HTML, not good for displaying on CLI. Cleanup from tags and entities before outputting.
3. A trivial bug fix at lines 271-272
4. Few doc cleanups
> [site:install] Small improvements

- src/Command/Debug/DatabaseTableCommand.php
- src/Command/Shared/ConnectTrait.php
This PR implement the sqlite support to https://github.com/hechoendrupal/drupal-console/issues/2447
```
drupalSqlite drupal debug:database:table
Showing tables for "/Users/hjuarez/drupalSqlite/web/sites/default/files/.ht.sqlite" database
------------------------------
Table
------------------------------
cache_container
cache_discovery
cache_bootstrap
cachetags
config
cache_config
key_value
key_value_expire
sequences
sessions
url_alias
semaphore
router
menu_tree
users_data
users
users_field_data
user__roles
cache_entity
cache_default
file_usage
file_managed
block_content
block_content_revision
block_content_field_data
block_content_field_revision
block_content__body
block_content_revision__body
node_access
node
node_revision
node_field_data
node_field_revision
node__body …
```
> [debug:database:table] Sqlite support

- src/Generator/FormAlterGenerator.php
- templates/module/help.php.twig
- templates/module/links.menu.yml.twig
- templates/module/routing-form.yml.twig
- templates/module/src/Form/form-alter.php.twig
- templates/module/src/Form/form-config.php.twig
- templates/module/src/Form/form.php.twig
The following commands were updated with code standard:
```
generate:form
generate:form:alter
generate:form:config
generate:help
generate:jstest
```
> [templates] Add code standard

- src/Command/Module/InstallCommand.php
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3254
> [module:install] Add dependencies validation

- src/Command/Debug/UpdateComposerCommand.php
- src/Command/Shared/UpdateTrait.php
- uninstall.services.yml
This PR should fix https://github.com/hechoendrupal/drupal-console/issues/3400
> [debug:update:composer] Add new command

- templates/module/src/Entity/Form/entity-content.php.twig
- Variable $entity is not used, so PHP CS is throwing a warning about an unused variable.
> Remove unused variable

- src/Command/Update/ExecuteCommand.php
> add capability to accept updates via command option

- src/Command/Create/UsersCommand.php
Time range question for `create:users` erroneously referred to nodes.
> [create:users] Fix time-range question

- config/services/database.yml
- uninstall.services.yml
This should be partially fixed.
https://github.com/hechoendrupal/drupal-console/issues/3514
> Execute database command without drupal boostap

- config/services/site.yml
- src/Command/Service/OverrideCommand.php
This PR is an extension of https://github.com/hechoendrupal/drupal-console/pull/3771
> [services:override] New command

- config/services/debug.yml
- src/Command/Debug/ModuleCommand.php
This PR should be fix https://github.com/hechoendrupal/drupal-console/issues/4114
> [debug:module] Allow multiple options

- src/Command/User/CreateCommand.php
This prevents an error from being thrown when constructing the success message.  See #4133.
> [user:create] Ensure $roles is an array when creating users.

- templates/module/src/Entity/entity-content.php.twig
This lack of ; was introduced in dd6492237
> Generate revisional entity content is broken

- src/Command/Generate/EntityContentCommand.php
- src/Generator/EntityContentGenerator.php
- templates/module/permissions-entity-content.yml.twig
- templates/module/src/Entity/entity-content.php.twig
- templates/module/src/accesscontrolhandler-entity-content.php.twig
- templates/module/src/entity-content-bundle-permissions.php.twig
PR for https://github.com/hechoendrupal/drupal-console/issues/3498
This patch generates bundle specific permissions related to CRUD with implementation and sets up permissions for revisioning but does not implement the checks as I did not see revisions in the UI.
(still little sketchy)
This depends on PR https://github.com/hechoendrupal/drupal-console/pull/4139 for revisionable.
```
rm -r modules/custom/test_changes
vendor/bin/drupal \
--no-interaction \
generate:module  \
--module="Test changes"  \
--machine-name="test_changes"  \
--module-path="modules/custom"  \
--description="Test changes done on drupal/console"  \
--core="8.x"  \
--package="Other"  \
--dependencies="" \
--module-file  \
--test
vendor/bin/drupal \
--no-interaction \
generate:entity:content  \
--module="test_changes" …
```
> Add bundle permissions for content entity

- src/Command/Database/AddCommand.php
- src/Generator/DatabaseSettingsGenerator.php
- templates/database/add-default.php.twig
This option allows to set the database as the default one instead of
adding a new database in addition to the default one.
See: https://github.com/hechoendrupal/drupal-console/issues/4142
> Add --default option to database:add

- src/Command/Config/ExportCommand.php
Fix path generating config:export. 
Generating the directory in root Drupal when is applied the next command.
```drupal config:export``` path relative
or 
```drupal config:export --directory=config2.test```
or 
```drupal config:export --directory="mod/config2.test"```
> Fix path config:export on root Drupal

- src/Command/Config/ExportCommand.php
Fix path directory generating drupal ```config:export --directory=config.test``` and to create config files as well in root dir.
Thanks.
> Fix path directory and to create config files

- templates/module/src/entity-content-bundle-permissions.php.twig
Hi,  ```generate:entity:content``` generate an error to the install.
Thanks
> Fix generate:entity:content installing module

- src/Generator/CacheContextGenerator.php
Hi,
A typo in CacheContextGenerator prevents the generation of files.
> [generate:cache:context] Typo in CacheContextGenerator

- config/services/generate.yml
- config/services/generator.yml
- src/Command/Generate/BlockTypeCommand.php
- src/Generator/BlockTypeGenerator.php
- templates/module/src/Plugin/Block/blocktype.php.twig
New command in order to generate a block content type and block type.
```$ drupal generate:block:type```
Additional the next https://github.com/hechoendrupal/drupal-console-en/pull/254
**Using**
Drupal Console        : 1.9.3
Drupal Console-en  : 1.9.3
Drupal core              : 8.7.7
Results Command.
1. ![blocktype](https://user-images.githubusercontent.com/6983125/65738650-38961c00-e0a8-11e9-9597-38cc30158f66.png)
2. ![blockcustom](https://user-images.githubusercontent.com/6983125/65738649-38961c00-e0a8-11e9-85ff-a7e84bc3c506.png)
Watch the video
https://youtu.be/xbx-dM1fT6I
> [generate:block:type] New command

- templates/module/src/Form/form.php.twig
> Use injected messenger service if possible.

- templates/module/src/Controller/controller.php.twig
- templates/module/src/Controller/entity-controller.php.twig
- templates/module/src/Entity/Form/entity-content-revision-delete.php.twig
- templates/module/src/Entity/Form/entity-content-revision-revert-translation.php.twig
- templates/module/src/Entity/Form/entity-content-revision-revert.php.twig
- templates/module/src/Entity/Form/entity-content.php.twig
- templates/module/src/Form/form-config.php.twig
- templates/module/src/Form/form.php.twig
- templates/module/src/Plugin/Block/block.php.twig
- templates/module/src/Plugin/Condition/condition.php.twig
- templates/module/src/Plugin/Field/FieldFormatter/imageformatter.php.twig
- templates/module/src/Plugin/Mail/mail.php.twig
- templates/module/src/Plugin/Rest/Resource/rest.php.twig
- templates/module/src/Plugin/skeleton.php.twig
This addresses https://github.com/hechoendrupal/drupal-console/issues/4169. 
It requires https://github.com/hechoendrupal/drupal-console-core/pull/369 to be merged first, for a few of the generators that use the function Twig function `serviceClassInjection`.
> Removes constructor override on service object generators.

- templates/theme/libraries.yml.twig
There is an indexation error in the template, the generated file is invalid
> [generate:theme] fix libraries.yml syntax

- src/Command/Site/InstallCommand.php
The issue that was addressed in commit e62a1fe #3930 #3931 is back.
If you submit an empty string as DB prefix (`--db-prefix=''`) it is handled exactly as if no db-prefix was given: the command asks for a prefix regardless of the input. This is due to a regression first introduced by f1dc3aa #3917. This regression was partly reverted by 1247f20 #4049, but in both cases **PHP’s implicit type casting** causes problems.
You have to check the input value explicitly against `null`, otherwise a blank string ("no prefix") will be handled like "no value given".
```php
if (!$something) {
echo '$something is either null or 0 or false or an empty array or an empty string. Are you sure this is the desired behavior?';
}
```
- Drupal version: tested on Drupal 8.6+
- Console version: Regression was …
> [site:install] Regression: command does not respect empty db-prefix

- templates/module/src/Plugin/Block/block.php.twig
- templates/module/src/Plugin/Field/FieldFormatter/imageformatter.php.twig
- templates/module/src/Plugin/Mail/mail.php.twig
- templates/module/src/Plugin/skeleton.php.twig
There was a bug on some of the templates on the previous PR I made.
When the class itself is implementing ContainerFactoryPluginInterface, there's no parent create method we can use. We should fallback to the class __construct() method instad.
This PR does just that.
> Bugfix for #4174.

- composer.json
- config/services/debug.yml
- config/services/rest.yml
- config/services/site.yml
- config/services/user.yml
- config/services/views.yml
- src/Application.php
- src/Command/Debug/UserCommand.php
- src/Command/Rest/EnableCommand.php
- src/Command/Site/StatisticsCommand.php
- src/Command/User/DeleteCommand.php
- src/Command/Views/DisableCommand.php
- src/Command/Views/EnableCommand.php
- src/Extension/Manager.php
- uninstall.services.yml
I removed the deprecated services and updated the symfony dependencies in order to be compatibles with Drupal 9
Major changes:
Remove support for PHP 5
Support for twig 2
Support for Symfony 4.4
> Drupal 9 Support

- src/Utils/Create/VocabularyData.php
Unicode::strtolower() was deprecated in D8 and isn't available in D9.
https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Component%21Utility%21Unicode.php/function/Unicode%3A%3Astrtolower/8.6.x
https://www.drupal.org/node/2850048
https://github.com/hechoendrupal/drupal-console/issues/4314
> Avoid removed 'Unicode::strtolower()'

- config/services/generate.yml
- config/services/generator.yml
On a new drupal install, I was getting errors for any console command I tried to run.
```
[ERROR] A "tags" entry must be an array for service "console.generate_ajax" in
/app/vendor/drupal/console//config/services/generate.yml. Check your YAML syntax.
```
```
[ERROR] A "tags" entry must be an array for service "console.ajax_command_generator" in
/app/vendor/drupal/console//config/services/generator.yml. Check your YAML syntax.
```
The culprit turned out to be trailing spaces in the Ajax generate commands. Not sure why this would cause an error, though I guess this is technically invalid YAML. In any case, removing the trailing whitespace resolved the issue.
> Fix errors from invalid YAML

- src/Command/Update/ExecuteCommand.php
This is just a simple fix which replaces the references to `\Drupal\Core\Extension\ModuleHandler` with it's respective interface `\Drupal\Core\Extension\ModuleHandlerInterface`.
Fixes #4333
> fix: Use service interfaces, not specific implementations.

- src/Bootstrap/DrupalServiceModifier.php
Fix #4310
Since the later arguments are required this should be all that's needed.
> Remove default parameter before required parameter

- templates/module/src/entity-content-bundle-permissions.php.twig
[generate:entity:content] wrongly creates one permission per entity (database row), instead of one permission per entity type.
> [generate:entity:content] per-bundle-permissions

- src/Command/Config/ExportCommand.php
- Use Drupal root, not Composer root.
- Avoid adding the root to an already absolute path.
- Avoid adding the root twice when creating the directory
Fixes #4245, fixes #4195, fixes #4198, fixes #4219
> [config:export] fix path construction (#4245)

- src/Command/Shared/EventsTrait.php
When calling `drupal generate:event:subscriber` : 
```
In EventsTrait.php line 59:
Undefined property: Drupal\Console\Command\Generate\EventSubscriberCommand::$events
```
The variable could either be in the trait or in the class using it. From what I've seen, it is only used in the EventSubscriberCommand class.
> fix: missing property

- src/Generator/BlockTypeGenerator.php
`block_description` is undefined, the one to use is `description`
> fix(generator): block description index

- templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
Throw Doctrine\Common\Annotations\AnnotationException
> [generate:plugin:field] Missing coma in fieldwidget.php.twig

- src/Generator/ComposerGenerator.php
Throws exception when unable to load module extension for module generator. Debugging/Addresses https://github.com/hechoendrupal/drupal-console/issues/4118
I'm not sure how you feel about calling out individual Issues in exception messages. But this seems like a highly specific problem anyway.
> Add Exception When Unable to load module from extensions. 

- templates/module/src/Plugin/Field/FieldWidget/fieldwidget.php.twig
If you generate a new field widget through the scaffolding command `drupal gpfw`, you can't use your widget right away due to a fatal error caused by a missing comma and annotations inclusion.
The attached PR fixes it.
> Fix fatal when scaffolding a FieldWidget.

- composer.json
The current module version isn't able to use on Drupal 10 implementations.
Some Drupal community members opened the https://www.drupal.org/project/console/issues/3337542 issue, reporting this compatibility issue and brought some fixes. These code modifications were brought by these members.
Please, update this module to cover the new Drupal's version.
> Issue #3337542: Drupal 10 compatibility fixes
